// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { RegistBankAccount } from './generated/definitions/RegistBankAccount';
import type { RegistBankAccountResponse } from './generated/definitions/RegistBankAccountResponse';
import type { RegistBankAccountEx } from './generated/definitions/RegistBankAccountEx';
import type { RegistBankAccountExResponse } from './generated/definitions/RegistBankAccountExResponse';
import type { RegistBankAccountsEx } from './generated/definitions/RegistBankAccountsEx';
import type { RegistBankAccountsExResponse } from './generated/definitions/RegistBankAccountsExResponse';
import type { UpdateBankAccount } from './generated/definitions/UpdateBankAccount';
import type { UpdateBankAccountResponse } from './generated/definitions/UpdateBankAccountResponse';
import type { UpdateBankAccountEx } from './generated/definitions/UpdateBankAccountEx';
import type { UpdateBankAccountExResponse } from './generated/definitions/UpdateBankAccountExResponse';
import type { StopBankAccount } from './generated/definitions/StopBankAccount';
import type { StopBankAccountResponse } from './generated/definitions/StopBankAccountResponse';
import type { CancelStopBankAccount } from './generated/definitions/CancelStopBankAccount';
import type { CancelStopBankAccountResponse } from './generated/definitions/CancelStopBankAccountResponse';
import type { ReRegistBankAccount } from './generated/definitions/ReRegistBankAccount';
import type { ReRegistBankAccountResponse } from './generated/definitions/ReRegistBankAccountResponse';
import type { RegistBankAccountLogMemo } from './generated/definitions/RegistBankAccountLogMemo';
import type { RegistBankAccountLogMemoResponse } from './generated/definitions/RegistBankAccountLogMemoResponse';
import type { GetBankAccount } from './generated/definitions/GetBankAccount';
import type { GetBankAccountResponse } from './generated/definitions/GetBankAccountResponse';
import type { GetBankAccountEx } from './generated/definitions/GetBankAccountEx';
import type { GetBankAccountExResponse } from './generated/definitions/GetBankAccountExResponse';
import type { GetBankAccountEx2 } from './generated/definitions/GetBankAccountEx2';
import type { GetBankAccountEx2Response } from './generated/definitions/GetBankAccountEx2Response';
import type { RefreshBankAccount } from './generated/definitions/RefreshBankAccount';
import type { RefreshBankAccountResponse } from './generated/definitions/RefreshBankAccountResponse';
import type { GetBankAccountLog } from './generated/definitions/GetBankAccountLog';
import type { GetBankAccountLogResponse } from './generated/definitions/GetBankAccountLogResponse';
import type { GetBankAccountLogEx } from './generated/definitions/GetBankAccountLogEx';
import type { GetBankAccountLogExResponse } from './generated/definitions/GetBankAccountLogExResponse';
import type { GetDailyBankAccountLog } from './generated/definitions/GetDailyBankAccountLog';
import type { GetDailyBankAccountLogResponse } from './generated/definitions/GetDailyBankAccountLogResponse';
import type { GetDailyBankAccountLogEx } from './generated/definitions/GetDailyBankAccountLogEx';
import type { GetDailyBankAccountLogExResponse } from './generated/definitions/GetDailyBankAccountLogExResponse';
import type { GetDailyBankAccountLogEx2 } from './generated/definitions/GetDailyBankAccountLogEx2';
import type { GetDailyBankAccountLogEx2Response } from './generated/definitions/GetDailyBankAccountLogEx2Response';
import type { GetDailyBankAccountTransLog } from './generated/definitions/GetDailyBankAccountTransLog';
import type { GetDailyBankAccountTransLogResponse } from './generated/definitions/GetDailyBankAccountTransLogResponse';
import type { GetMonthlyBankAccountLog } from './generated/definitions/GetMonthlyBankAccountLog';
import type { GetMonthlyBankAccountLogResponse } from './generated/definitions/GetMonthlyBankAccountLogResponse';
import type { GetMonthlyBankAccountLogEx } from './generated/definitions/GetMonthlyBankAccountLogEx';
import type { GetMonthlyBankAccountLogExResponse } from './generated/definitions/GetMonthlyBankAccountLogExResponse';
import type { GetMonthlyBankAccountLogEx2 } from './generated/definitions/GetMonthlyBankAccountLogEx2';
import type { GetMonthlyBankAccountLogEx2Response } from './generated/definitions/GetMonthlyBankAccountLogEx2Response';
import type { GetMonthlyBankAccountTransLog } from './generated/definitions/GetMonthlyBankAccountTransLog';
import type { GetMonthlyBankAccountTransLogResponse } from './generated/definitions/GetMonthlyBankAccountTransLogResponse';
import type { GetPeriodBankAccountLog } from './generated/definitions/GetPeriodBankAccountLog';
import type { GetPeriodBankAccountLogResponse } from './generated/definitions/GetPeriodBankAccountLogResponse';
import type { GetPeriodBankAccountLogEx } from './generated/definitions/GetPeriodBankAccountLogEx';
import type { GetPeriodBankAccountLogExResponse } from './generated/definitions/GetPeriodBankAccountLogExResponse';
import type { GetPeriodBankAccountLogEx2 } from './generated/definitions/GetPeriodBankAccountLogEx2';
import type { GetPeriodBankAccountLogEx2Response } from './generated/definitions/GetPeriodBankAccountLogEx2Response';
import type { GetPeriodBankAccountTransLog } from './generated/definitions/GetPeriodBankAccountTransLog';
import type { GetPeriodBankAccountTransLogResponse } from './generated/definitions/GetPeriodBankAccountTransLogResponse';
import type { GetBankAccountScrapRequestUrl } from './generated/definitions/GetBankAccountScrapRequestUrl';
import type { GetBankAccountScrapRequestUrlResponse } from './generated/definitions/GetBankAccountScrapRequestUrlResponse';
import type { GetBankAccountManagementUrl } from './generated/definitions/GetBankAccountManagementUrl';
import type { GetBankAccountManagementUrlResponse } from './generated/definitions/GetBankAccountManagementUrlResponse';
import type { GetBankAccountLogUrl } from './generated/definitions/GetBankAccountLogUrl';
import type { GetBankAccountLogUrlResponse } from './generated/definitions/GetBankAccountLogUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class BankAccountClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'BANKACCOUNT';
  }

  static async create(config: BarobillConfig): Promise<BankAccountClient> {
    const client = new BankAccountClient(config);
    await client.init();
    return client;
  }

  async registBankAccount(params: Omit<RegistBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistBankAccountResponse> {
    return this.call<RegistBankAccountResponse>('RegistBankAccount', params);
  }

  async registBankAccountEx(params: Omit<RegistBankAccountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistBankAccountExResponse> {
    return this.call<RegistBankAccountExResponse>('RegistBankAccountEx', params);
  }

  async registBankAccountsEx(params: Omit<RegistBankAccountsEx, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistBankAccountsExResponse> {
    return this.call<RegistBankAccountsExResponse>('RegistBankAccountsEx', params);
  }

  async updateBankAccount(params: Omit<UpdateBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateBankAccountResponse> {
    return this.call<UpdateBankAccountResponse>('UpdateBankAccount', params);
  }

  async updateBankAccountEx(params: Omit<UpdateBankAccountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateBankAccountExResponse> {
    return this.call<UpdateBankAccountExResponse>('UpdateBankAccountEx', params);
  }

  async stopBankAccount(params: Omit<StopBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<StopBankAccountResponse> {
    return this.call<StopBankAccountResponse>('StopBankAccount', params);
  }

  async cancelStopBankAccount(params: Omit<CancelStopBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<CancelStopBankAccountResponse> {
    return this.call<CancelStopBankAccountResponse>('CancelStopBankAccount', params);
  }

  async reRegistBankAccount(params: Omit<ReRegistBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<ReRegistBankAccountResponse> {
    return this.call<ReRegistBankAccountResponse>('ReRegistBankAccount', params);
  }

  async registBankAccountLogMemo(params: Omit<RegistBankAccountLogMemo, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistBankAccountLogMemoResponse> {
    return this.call<RegistBankAccountLogMemoResponse>('RegistBankAccountLogMemo', params);
  }

  async getBankAccount(params: Omit<GetBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountResponse> {
    return this.call<GetBankAccountResponse>('GetBankAccount', params);
  }

  async getBankAccountEx(params: Omit<GetBankAccountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountExResponse> {
    return this.call<GetBankAccountExResponse>('GetBankAccountEx', params);
  }

  async getBankAccountEx2(params: Omit<GetBankAccountEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountEx2Response> {
    return this.call<GetBankAccountEx2Response>('GetBankAccountEx2', params);
  }

  async refreshBankAccount(params: Omit<RefreshBankAccount, 'CERTKEY'> & { CorpNum?: string }): Promise<RefreshBankAccountResponse> {
    return this.call<RefreshBankAccountResponse>('RefreshBankAccount', params);
  }

  async getBankAccountLog(params: Omit<GetBankAccountLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountLogResponse> {
    return this.call<GetBankAccountLogResponse>('GetBankAccountLog', params);
  }

  async getBankAccountLogEx(params: Omit<GetBankAccountLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountLogExResponse> {
    return this.call<GetBankAccountLogExResponse>('GetBankAccountLogEx', params);
  }

  async getDailyBankAccountLog(params: Omit<GetDailyBankAccountLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyBankAccountLogResponse> {
    return this.call<GetDailyBankAccountLogResponse>('GetDailyBankAccountLog', params);
  }

  async getDailyBankAccountLogEx(params: Omit<GetDailyBankAccountLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyBankAccountLogExResponse> {
    return this.call<GetDailyBankAccountLogExResponse>('GetDailyBankAccountLogEx', params);
  }

  async getDailyBankAccountLogEx2(params: Omit<GetDailyBankAccountLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyBankAccountLogEx2Response> {
    return this.call<GetDailyBankAccountLogEx2Response>('GetDailyBankAccountLogEx2', params);
  }

  async getDailyBankAccountTransLog(params: Omit<GetDailyBankAccountTransLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyBankAccountTransLogResponse> {
    return this.call<GetDailyBankAccountTransLogResponse>('GetDailyBankAccountTransLog', params);
  }

  async getMonthlyBankAccountLog(params: Omit<GetMonthlyBankAccountLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyBankAccountLogResponse> {
    return this.call<GetMonthlyBankAccountLogResponse>('GetMonthlyBankAccountLog', params);
  }

  async getMonthlyBankAccountLogEx(params: Omit<GetMonthlyBankAccountLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyBankAccountLogExResponse> {
    return this.call<GetMonthlyBankAccountLogExResponse>('GetMonthlyBankAccountLogEx', params);
  }

  async getMonthlyBankAccountLogEx2(params: Omit<GetMonthlyBankAccountLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyBankAccountLogEx2Response> {
    return this.call<GetMonthlyBankAccountLogEx2Response>('GetMonthlyBankAccountLogEx2', params);
  }

  async getMonthlyBankAccountTransLog(params: Omit<GetMonthlyBankAccountTransLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyBankAccountTransLogResponse> {
    return this.call<GetMonthlyBankAccountTransLogResponse>('GetMonthlyBankAccountTransLog', params);
  }

  async getPeriodBankAccountLog(params: Omit<GetPeriodBankAccountLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodBankAccountLogResponse> {
    return this.call<GetPeriodBankAccountLogResponse>('GetPeriodBankAccountLog', params);
  }

  async getPeriodBankAccountLogEx(params: Omit<GetPeriodBankAccountLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodBankAccountLogExResponse> {
    return this.call<GetPeriodBankAccountLogExResponse>('GetPeriodBankAccountLogEx', params);
  }

  async getPeriodBankAccountLogEx2(params: Omit<GetPeriodBankAccountLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodBankAccountLogEx2Response> {
    return this.call<GetPeriodBankAccountLogEx2Response>('GetPeriodBankAccountLogEx2', params);
  }

  async getPeriodBankAccountTransLog(params: Omit<GetPeriodBankAccountTransLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodBankAccountTransLogResponse> {
    return this.call<GetPeriodBankAccountTransLogResponse>('GetPeriodBankAccountTransLog', params);
  }

  async getBankAccountScrapRequestURL(params: Omit<GetBankAccountScrapRequestUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountScrapRequestUrlResponse> {
    return this.call<GetBankAccountScrapRequestUrlResponse>('GetBankAccountScrapRequestURL', params);
  }

  async getBankAccountManagementURL(params: Omit<GetBankAccountManagementUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountManagementUrlResponse> {
    return this.call<GetBankAccountManagementUrlResponse>('GetBankAccountManagementURL', params);
  }

  async getBankAccountLogURL(params: Omit<GetBankAccountLogUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankAccountLogUrlResponse> {
    return this.call<GetBankAccountLogUrlResponse>('GetBankAccountLogURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY'> & { CorpNum?: string }): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
