// This file is auto-generated by scripts/generate-wrapper.ts
export { BankAccountClient } from './client';
export type { BarobillConfig } from '@barobill-sdk/core';
export * from './generated/index';
