// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { RegistCard } from './generated/definitions/RegistCard';
import type { RegistCardResponse } from './generated/definitions/RegistCardResponse';
import type { RegistCardEx } from './generated/definitions/RegistCardEx';
import type { RegistCardExResponse } from './generated/definitions/RegistCardExResponse';
import type { RegistCardsEx } from './generated/definitions/RegistCardsEx';
import type { RegistCardsExResponse } from './generated/definitions/RegistCardsExResponse';
import type { UpdateCard } from './generated/definitions/UpdateCard';
import type { UpdateCardResponse } from './generated/definitions/UpdateCardResponse';
import type { StopCard } from './generated/definitions/StopCard';
import type { StopCardResponse } from './generated/definitions/StopCardResponse';
import type { CancelStopCard } from './generated/definitions/CancelStopCard';
import type { CancelStopCardResponse } from './generated/definitions/CancelStopCardResponse';
import type { ReRegistCard } from './generated/definitions/ReRegistCard';
import type { ReRegistCardResponse } from './generated/definitions/ReRegistCardResponse';
import type { RegistCardLogMemo } from './generated/definitions/RegistCardLogMemo';
import type { RegistCardLogMemoResponse } from './generated/definitions/RegistCardLogMemoResponse';
import type { GetCard } from './generated/definitions/GetCard';
import type { GetCardResponse } from './generated/definitions/GetCardResponse';
import type { GetCardEx } from './generated/definitions/GetCardEx';
import type { GetCardExResponse } from './generated/definitions/GetCardExResponse';
import type { GetCardEx2 } from './generated/definitions/GetCardEx2';
import type { GetCardEx2Response } from './generated/definitions/GetCardEx2Response';
import type { RefreshCard } from './generated/definitions/RefreshCard';
import type { RefreshCardResponse } from './generated/definitions/RefreshCardResponse';
import type { GetCardLog } from './generated/definitions/GetCardLog';
import type { GetCardLogResponse } from './generated/definitions/GetCardLogResponse';
import type { GetCardLogEx } from './generated/definitions/GetCardLogEx';
import type { GetCardLogExResponse } from './generated/definitions/GetCardLogExResponse';
import type { GetDailyCardLog } from './generated/definitions/GetDailyCardLog';
import type { GetDailyCardLogResponse } from './generated/definitions/GetDailyCardLogResponse';
import type { GetDailyCardLogEx } from './generated/definitions/GetDailyCardLogEx';
import type { GetDailyCardLogExResponse } from './generated/definitions/GetDailyCardLogExResponse';
import type { GetDailyCardLogEx2 } from './generated/definitions/GetDailyCardLogEx2';
import type { GetDailyCardLogEx2Response } from './generated/definitions/GetDailyCardLogEx2Response';
import type { GetDailyCardLogEx3 } from './generated/definitions/GetDailyCardLogEx3';
import type { GetDailyCardLogEx3Response } from './generated/definitions/GetDailyCardLogEx3Response';
import type { GetDailyCardApprovalLog } from './generated/definitions/GetDailyCardApprovalLog';
import type { GetDailyCardApprovalLogResponse } from './generated/definitions/GetDailyCardApprovalLogResponse';
import type { GetMonthlyCardLog } from './generated/definitions/GetMonthlyCardLog';
import type { GetMonthlyCardLogResponse } from './generated/definitions/GetMonthlyCardLogResponse';
import type { GetMonthlyCardLogEx } from './generated/definitions/GetMonthlyCardLogEx';
import type { GetMonthlyCardLogExResponse } from './generated/definitions/GetMonthlyCardLogExResponse';
import type { GetMonthlyCardLogEx2 } from './generated/definitions/GetMonthlyCardLogEx2';
import type { GetMonthlyCardLogEx2Response } from './generated/definitions/GetMonthlyCardLogEx2Response';
import type { GetMonthlyCardLogEx3 } from './generated/definitions/GetMonthlyCardLogEx3';
import type { GetMonthlyCardLogEx3Response } from './generated/definitions/GetMonthlyCardLogEx3Response';
import type { GetMonthlyCardApprovalLog } from './generated/definitions/GetMonthlyCardApprovalLog';
import type { GetMonthlyCardApprovalLogResponse } from './generated/definitions/GetMonthlyCardApprovalLogResponse';
import type { GetPeriodCardLog } from './generated/definitions/GetPeriodCardLog';
import type { GetPeriodCardLogResponse } from './generated/definitions/GetPeriodCardLogResponse';
import type { GetPeriodCardLogEx } from './generated/definitions/GetPeriodCardLogEx';
import type { GetPeriodCardLogExResponse } from './generated/definitions/GetPeriodCardLogExResponse';
import type { GetPeriodCardLogEx2 } from './generated/definitions/GetPeriodCardLogEx2';
import type { GetPeriodCardLogEx2Response } from './generated/definitions/GetPeriodCardLogEx2Response';
import type { GetPeriodCardLogEx3 } from './generated/definitions/GetPeriodCardLogEx3';
import type { GetPeriodCardLogEx3Response } from './generated/definitions/GetPeriodCardLogEx3Response';
import type { GetPeriodCardApprovalLog } from './generated/definitions/GetPeriodCardApprovalLog';
import type { GetPeriodCardApprovalLogResponse } from './generated/definitions/GetPeriodCardApprovalLogResponse';
import type { GetCardScrapRequestUrl } from './generated/definitions/GetCardScrapRequestUrl';
import type { GetCardScrapRequestUrlResponse } from './generated/definitions/GetCardScrapRequestUrlResponse';
import type { GetCardManagementUrl } from './generated/definitions/GetCardManagementUrl';
import type { GetCardManagementUrlResponse } from './generated/definitions/GetCardManagementUrlResponse';
import type { GetCardLogUrl } from './generated/definitions/GetCardLogUrl';
import type { GetCardLogUrlResponse } from './generated/definitions/GetCardLogUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class CardClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'CARD';
  }

  static async create(config: BarobillConfig): Promise<CardClient> {
    const client = new CardClient(config);
    await client.init();
    return client;
  }

  async registCard(params: Omit<RegistCard, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCardResponse> {
    return this.call<RegistCardResponse>('RegistCard', params);
  }

  async registCardEx(params: Omit<RegistCardEx, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCardExResponse> {
    return this.call<RegistCardExResponse>('RegistCardEx', params);
  }

  async registCardsEx(params: Omit<RegistCardsEx, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCardsExResponse> {
    return this.call<RegistCardsExResponse>('RegistCardsEx', params);
  }

  async updateCard(params: Omit<UpdateCard, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateCardResponse> {
    return this.call<UpdateCardResponse>('UpdateCard', params);
  }

  async stopCard(params: Omit<StopCard, 'CERTKEY'> & { CorpNum?: string }): Promise<StopCardResponse> {
    return this.call<StopCardResponse>('StopCard', params);
  }

  async cancelStopCard(params: Omit<CancelStopCard, 'CERTKEY'> & { CorpNum?: string }): Promise<CancelStopCardResponse> {
    return this.call<CancelStopCardResponse>('CancelStopCard', params);
  }

  async reRegistCard(params: Omit<ReRegistCard, 'CERTKEY'> & { CorpNum?: string }): Promise<ReRegistCardResponse> {
    return this.call<ReRegistCardResponse>('ReRegistCard', params);
  }

  async registCardLogMemo(params: Omit<RegistCardLogMemo, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCardLogMemoResponse> {
    return this.call<RegistCardLogMemoResponse>('RegistCardLogMemo', params);
  }

  async getCard(params: Omit<GetCard, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardResponse> {
    return this.call<GetCardResponse>('GetCard', params);
  }

  async getCardEx(params: Omit<GetCardEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardExResponse> {
    return this.call<GetCardExResponse>('GetCardEx', params);
  }

  async getCardEx2(params: Omit<GetCardEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardEx2Response> {
    return this.call<GetCardEx2Response>('GetCardEx2', params);
  }

  async refreshCard(params: Omit<RefreshCard, 'CERTKEY'> & { CorpNum?: string }): Promise<RefreshCardResponse> {
    return this.call<RefreshCardResponse>('RefreshCard', params);
  }

  async getCardLog(params: Omit<GetCardLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardLogResponse> {
    return this.call<GetCardLogResponse>('GetCardLog', params);
  }

  async getCardLogEx(params: Omit<GetCardLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardLogExResponse> {
    return this.call<GetCardLogExResponse>('GetCardLogEx', params);
  }

  async getDailyCardLog(params: Omit<GetDailyCardLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyCardLogResponse> {
    return this.call<GetDailyCardLogResponse>('GetDailyCardLog', params);
  }

  async getDailyCardLogEx(params: Omit<GetDailyCardLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyCardLogExResponse> {
    return this.call<GetDailyCardLogExResponse>('GetDailyCardLogEx', params);
  }

  async getDailyCardLogEx2(params: Omit<GetDailyCardLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyCardLogEx2Response> {
    return this.call<GetDailyCardLogEx2Response>('GetDailyCardLogEx2', params);
  }

  async getDailyCardLogEx3(params: Omit<GetDailyCardLogEx3, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyCardLogEx3Response> {
    return this.call<GetDailyCardLogEx3Response>('GetDailyCardLogEx3', params);
  }

  async getDailyCardApprovalLog(params: Omit<GetDailyCardApprovalLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetDailyCardApprovalLogResponse> {
    return this.call<GetDailyCardApprovalLogResponse>('GetDailyCardApprovalLog', params);
  }

  async getMonthlyCardLog(params: Omit<GetMonthlyCardLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyCardLogResponse> {
    return this.call<GetMonthlyCardLogResponse>('GetMonthlyCardLog', params);
  }

  async getMonthlyCardLogEx(params: Omit<GetMonthlyCardLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyCardLogExResponse> {
    return this.call<GetMonthlyCardLogExResponse>('GetMonthlyCardLogEx', params);
  }

  async getMonthlyCardLogEx2(params: Omit<GetMonthlyCardLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyCardLogEx2Response> {
    return this.call<GetMonthlyCardLogEx2Response>('GetMonthlyCardLogEx2', params);
  }

  async getMonthlyCardLogEx3(params: Omit<GetMonthlyCardLogEx3, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyCardLogEx3Response> {
    return this.call<GetMonthlyCardLogEx3Response>('GetMonthlyCardLogEx3', params);
  }

  async getMonthlyCardApprovalLog(params: Omit<GetMonthlyCardApprovalLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetMonthlyCardApprovalLogResponse> {
    return this.call<GetMonthlyCardApprovalLogResponse>('GetMonthlyCardApprovalLog', params);
  }

  async getPeriodCardLog(params: Omit<GetPeriodCardLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodCardLogResponse> {
    return this.call<GetPeriodCardLogResponse>('GetPeriodCardLog', params);
  }

  async getPeriodCardLogEx(params: Omit<GetPeriodCardLogEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodCardLogExResponse> {
    return this.call<GetPeriodCardLogExResponse>('GetPeriodCardLogEx', params);
  }

  async getPeriodCardLogEx2(params: Omit<GetPeriodCardLogEx2, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodCardLogEx2Response> {
    return this.call<GetPeriodCardLogEx2Response>('GetPeriodCardLogEx2', params);
  }

  async getPeriodCardLogEx3(params: Omit<GetPeriodCardLogEx3, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodCardLogEx3Response> {
    return this.call<GetPeriodCardLogEx3Response>('GetPeriodCardLogEx3', params);
  }

  async getPeriodCardApprovalLog(params: Omit<GetPeriodCardApprovalLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetPeriodCardApprovalLogResponse> {
    return this.call<GetPeriodCardApprovalLogResponse>('GetPeriodCardApprovalLog', params);
  }

  async getCardScrapRequestURL(params: Omit<GetCardScrapRequestUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardScrapRequestUrlResponse> {
    return this.call<GetCardScrapRequestUrlResponse>('GetCardScrapRequestURL', params);
  }

  async getCardManagementURL(params: Omit<GetCardManagementUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardManagementUrlResponse> {
    return this.call<GetCardManagementUrlResponse>('GetCardManagementURL', params);
  }

  async getCardLogURL(params: Omit<GetCardLogUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCardLogUrlResponse> {
    return this.call<GetCardLogUrlResponse>('GetCardLogURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY'> & { CorpNum?: string }): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
