// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { CheckMgtKeyIsExists } from './generated/definitions/CheckMgtKeyIsExists';
import type { CheckMgtKeyIsExistsResponse } from './generated/definitions/CheckMgtKeyIsExistsResponse';
import type { CheckIsValidCashBill } from './generated/definitions/CheckIsValidCashBill';
import type { CheckIsValidCashBillResponse } from './generated/definitions/CheckIsValidCashBillResponse';
import type { CheckIsValidCashBillEx } from './generated/definitions/CheckIsValidCashBillEx';
import type { CheckIsValidCashBillExResponse } from './generated/definitions/CheckIsValidCashBillExResponse';
import type { RegistCashBill } from './generated/definitions/RegistCashBill';
import type { RegistCashBillResponse } from './generated/definitions/RegistCashBillResponse';
import type { RegistCashBillEx } from './generated/definitions/RegistCashBillEx';
import type { RegistCashBillExResponse } from './generated/definitions/RegistCashBillExResponse';
import type { UpdateCashBill } from './generated/definitions/UpdateCashBill';
import type { UpdateCashBillResponse } from './generated/definitions/UpdateCashBillResponse';
import type { UpdateCashBillEx } from './generated/definitions/UpdateCashBillEx';
import type { UpdateCashBillExResponse } from './generated/definitions/UpdateCashBillExResponse';
import type { DeleteCashBill } from './generated/definitions/DeleteCashBill';
import type { DeleteCashBillResponse } from './generated/definitions/DeleteCashBillResponse';
import type { IssueCashBill } from './generated/definitions/IssueCashBill';
import type { IssueCashBillResponse } from './generated/definitions/IssueCashBillResponse';
import type { CancelCashBill } from './generated/definitions/CancelCashBill';
import type { CancelCashBillResponse } from './generated/definitions/CancelCashBillResponse';
import type { CancelCashBillPartial } from './generated/definitions/CancelCashBillPartial';
import type { CancelCashBillPartialResponse } from './generated/definitions/CancelCashBillPartialResponse';
import type { CancelCashBillEx } from './generated/definitions/CancelCashBillEx';
import type { CancelCashBillExResponse } from './generated/definitions/CancelCashBillExResponse';
import type { CancelCashBillPartialEx } from './generated/definitions/CancelCashBillPartialEx';
import type { CancelCashBillPartialExResponse } from './generated/definitions/CancelCashBillPartialExResponse';
import type { CancelCashBillBeforeNtsSend } from './generated/definitions/CancelCashBillBeforeNtsSend';
import type { CancelCashBillBeforeNtsSendResponse } from './generated/definitions/CancelCashBillBeforeNtsSendResponse';
import type { GetCancelableAmount } from './generated/definitions/GetCancelableAmount';
import type { GetCancelableAmountResponse } from './generated/definitions/GetCancelableAmountResponse';
import type { RegistAndIssueCashBill } from './generated/definitions/RegistAndIssueCashBill';
import type { RegistAndIssueCashBillResponse } from './generated/definitions/RegistAndIssueCashBillResponse';
import type { GetCashBill } from './generated/definitions/GetCashBill';
import type { GetCashBillResponse } from './generated/definitions/GetCashBillResponse';
import type { GetCashBillEx } from './generated/definitions/GetCashBillEx';
import type { GetCashBillExResponse } from './generated/definitions/GetCashBillExResponse';
import type { GetCashBillExNk } from './generated/definitions/GetCashBillExNk';
import type { GetCashBillExNkResponse } from './generated/definitions/GetCashBillExNkResponse';
import type { GetCashBillState } from './generated/definitions/GetCashBillState';
import type { GetCashBillStateResponse } from './generated/definitions/GetCashBillStateResponse';
import type { GetCashBillStates } from './generated/definitions/GetCashBillStates';
import type { GetCashBillStatesResponse } from './generated/definitions/GetCashBillStatesResponse';
import type { GetCashBillLog } from './generated/definitions/GetCashBillLog';
import type { GetCashBillLogResponse } from './generated/definitions/GetCashBillLogResponse';
import type { GetCancelCashBills } from './generated/definitions/GetCancelCashBills';
import type { GetCancelCashBillsResponse } from './generated/definitions/GetCancelCashBillsResponse';
import type { SendEmailEx } from './generated/definitions/SendEmailEx';
import type { SendEmailExResponse } from './generated/definitions/SendEmailExResponse';
import type { SendMessageEx } from './generated/definitions/SendMessageEx';
import type { SendMessageExResponse } from './generated/definitions/SendMessageExResponse';
import type { SendFaxEx } from './generated/definitions/SendFaxEx';
import type { SendFaxExResponse } from './generated/definitions/SendFaxExResponse';
import type { SendEmail } from './generated/definitions/SendEmail';
import type { SendEmailResponse } from './generated/definitions/SendEmailResponse';
import type { SendSms } from './generated/definitions/SendSms';
import type { SendSmsResponse } from './generated/definitions/SendSmsResponse';
import type { SendFax } from './generated/definitions/SendFax';
import type { SendFaxResponse } from './generated/definitions/SendFaxResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetCashBillPopUpUrl } from './generated/definitions/GetCashBillPopUpUrl';
import type { GetCashBillPopUpUrlResponse } from './generated/definitions/GetCashBillPopUpUrlResponse';
import type { GetCashBillPopUpUrlnk } from './generated/definitions/GetCashBillPopUpUrlnk';
import type { GetCashBillPopUpUrlnkResponse } from './generated/definitions/GetCashBillPopUpUrlnkResponse';
import type { GetCashBillPrintUrl } from './generated/definitions/GetCashBillPrintUrl';
import type { GetCashBillPrintUrlResponse } from './generated/definitions/GetCashBillPrintUrlResponse';
import type { GetCashBillPrintUrlnk } from './generated/definitions/GetCashBillPrintUrlnk';
import type { GetCashBillPrintUrlnkResponse } from './generated/definitions/GetCashBillPrintUrlnkResponse';
import type { GetCashBillsPrintUrl } from './generated/definitions/GetCashBillsPrintUrl';
import type { GetCashBillsPrintUrlResponse } from './generated/definitions/GetCashBillsPrintUrlResponse';
import type { GetCashBillMailUrl } from './generated/definitions/GetCashBillMailUrl';
import type { GetCashBillMailUrlResponse } from './generated/definitions/GetCashBillMailUrlResponse';
import type { GetCashBillMailUrlnk } from './generated/definitions/GetCashBillMailUrlnk';
import type { GetCashBillMailUrlnkResponse } from './generated/definitions/GetCashBillMailUrlnkResponse';
import type { GetCashBillSalesList } from './generated/definitions/GetCashBillSalesList';
import type { GetCashBillSalesListResponse } from './generated/definitions/GetCashBillSalesListResponse';
import type { GetCashBillSalesListEx } from './generated/definitions/GetCashBillSalesListEx';
import type { GetCashBillSalesListExResponse } from './generated/definitions/GetCashBillSalesListExResponse';
import type { GetCashBillPurchaseList } from './generated/definitions/GetCashBillPurchaseList';
import type { GetCashBillPurchaseListResponse } from './generated/definitions/GetCashBillPurchaseListResponse';
import type { GetCashBillPurchaseListEx } from './generated/definitions/GetCashBillPurchaseListEx';
import type { GetCashBillPurchaseListExResponse } from './generated/definitions/GetCashBillPurchaseListExResponse';
import type { GetDailyCashBillSalesList } from './generated/definitions/GetDailyCashBillSalesList';
import type { GetDailyCashBillSalesListResponse } from './generated/definitions/GetDailyCashBillSalesListResponse';
import type { GetDailyCashBillSalesListEx } from './generated/definitions/GetDailyCashBillSalesListEx';
import type { GetDailyCashBillSalesListExResponse } from './generated/definitions/GetDailyCashBillSalesListExResponse';
import type { GetDailyCashBillPurchaseList } from './generated/definitions/GetDailyCashBillPurchaseList';
import type { GetDailyCashBillPurchaseListResponse } from './generated/definitions/GetDailyCashBillPurchaseListResponse';
import type { GetDailyCashBillPurchaseListEx } from './generated/definitions/GetDailyCashBillPurchaseListEx';
import type { GetDailyCashBillPurchaseListExResponse } from './generated/definitions/GetDailyCashBillPurchaseListExResponse';
import type { GetMonthlyCashBillSalesList } from './generated/definitions/GetMonthlyCashBillSalesList';
import type { GetMonthlyCashBillSalesListResponse } from './generated/definitions/GetMonthlyCashBillSalesListResponse';
import type { GetMonthlyCashBillSalesListEx } from './generated/definitions/GetMonthlyCashBillSalesListEx';
import type { GetMonthlyCashBillSalesListExResponse } from './generated/definitions/GetMonthlyCashBillSalesListExResponse';
import type { GetMonthlyCashBillPurchaseList } from './generated/definitions/GetMonthlyCashBillPurchaseList';
import type { GetMonthlyCashBillPurchaseListResponse } from './generated/definitions/GetMonthlyCashBillPurchaseListResponse';
import type { GetMonthlyCashBillPurchaseListEx } from './generated/definitions/GetMonthlyCashBillPurchaseListEx';
import type { GetMonthlyCashBillPurchaseListExResponse } from './generated/definitions/GetMonthlyCashBillPurchaseListExResponse';
import type { GetPeriodCashBillSalesList } from './generated/definitions/GetPeriodCashBillSalesList';
import type { GetPeriodCashBillSalesListResponse } from './generated/definitions/GetPeriodCashBillSalesListResponse';
import type { GetPeriodCashBillSalesListEx } from './generated/definitions/GetPeriodCashBillSalesListEx';
import type { GetPeriodCashBillSalesListExResponse } from './generated/definitions/GetPeriodCashBillSalesListExResponse';
import type { GetPeriodCashBillPurchaseList } from './generated/definitions/GetPeriodCashBillPurchaseList';
import type { GetPeriodCashBillPurchaseListResponse } from './generated/definitions/GetPeriodCashBillPurchaseListResponse';
import type { GetPeriodCashBillPurchaseListEx } from './generated/definitions/GetPeriodCashBillPurchaseListEx';
import type { GetPeriodCashBillPurchaseListExResponse } from './generated/definitions/GetPeriodCashBillPurchaseListExResponse';
import type { GetCashBillSalesListById } from './generated/definitions/GetCashBillSalesListById';
import type { GetCashBillSalesListByIdResponse } from './generated/definitions/GetCashBillSalesListByIdResponse';
import type { GetCashBillPurchaseListById } from './generated/definitions/GetCashBillPurchaseListById';
import type { GetCashBillPurchaseListByIdResponse } from './generated/definitions/GetCashBillPurchaseListByIdResponse';
import type { RegistCashBillScrap } from './generated/definitions/RegistCashBillScrap';
import type { RegistCashBillScrapResponse } from './generated/definitions/RegistCashBillScrapResponse';
import type { RegistCashBillScrapEx } from './generated/definitions/RegistCashBillScrapEx';
import type { RegistCashBillScrapExResponse } from './generated/definitions/RegistCashBillScrapExResponse';
import type { UpdateCashBillScrap } from './generated/definitions/UpdateCashBillScrap';
import type { UpdateCashBillScrapResponse } from './generated/definitions/UpdateCashBillScrapResponse';
import type { UpdateCashBillScrapEx } from './generated/definitions/UpdateCashBillScrapEx';
import type { UpdateCashBillScrapExResponse } from './generated/definitions/UpdateCashBillScrapExResponse';
import type { StopCashBillScrap } from './generated/definitions/StopCashBillScrap';
import type { StopCashBillScrapResponse } from './generated/definitions/StopCashBillScrapResponse';
import type { CancelStopCashBillScrap } from './generated/definitions/CancelStopCashBillScrap';
import type { CancelStopCashBillScrapResponse } from './generated/definitions/CancelStopCashBillScrapResponse';
import type { ReRegistCashBillScrap } from './generated/definitions/ReRegistCashBillScrap';
import type { ReRegistCashBillScrapResponse } from './generated/definitions/ReRegistCashBillScrapResponse';
import type { GetCashBillScrapRequestUrl } from './generated/definitions/GetCashBillScrapRequestUrl';
import type { GetCashBillScrapRequestUrlResponse } from './generated/definitions/GetCashBillScrapRequestUrlResponse';
import type { RefreshCashBillScrap } from './generated/definitions/RefreshCashBillScrap';
import type { RefreshCashBillScrapResponse } from './generated/definitions/RefreshCashBillScrapResponse';
import type { MakeDocLinkage } from './generated/definitions/MakeDocLinkage';
import type { MakeDocLinkageResponse } from './generated/definitions/MakeDocLinkageResponse';
import type { RemoveDocLinkage } from './generated/definitions/RemoveDocLinkage';
import type { RemoveDocLinkageResponse } from './generated/definitions/RemoveDocLinkageResponse';
import type { GetLinkedDocs } from './generated/definitions/GetLinkedDocs';
import type { GetLinkedDocsResponse } from './generated/definitions/GetLinkedDocsResponse';
import type { GetJicInRegistUrl } from './generated/definitions/GetJicInRegistUrl';
import type { GetJicInRegistUrlResponse } from './generated/definitions/GetJicInRegistUrlResponse';
import type { GetBusinessLicenseRegistUrl } from './generated/definitions/GetBusinessLicenseRegistUrl';
import type { GetBusinessLicenseRegistUrlResponse } from './generated/definitions/GetBusinessLicenseRegistUrlResponse';
import type { GetBankBookRegistUrl } from './generated/definitions/GetBankBookRegistUrl';
import type { GetBankBookRegistUrlResponse } from './generated/definitions/GetBankBookRegistUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class CashbillClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'CASHBILL';
  }

  static async create(config: BarobillConfig): Promise<CashbillClient> {
    const client = new CashbillClient(config);
    await client.init();
    return client;
  }

  async checkMgtKeyIsExists(params: Omit<CheckMgtKeyIsExists, 'CERTKEY' | 'CorpNum'>): Promise<CheckMgtKeyIsExistsResponse> {
    return this.call<CheckMgtKeyIsExistsResponse>('CheckMgtKeyIsExists', params);
  }

  async checkIsValidCashBill(params: Omit<CheckIsValidCashBill, 'CERTKEY' | 'CorpNum'>): Promise<CheckIsValidCashBillResponse> {
    return this.call<CheckIsValidCashBillResponse>('CheckIsValidCashBill', params);
  }

  async checkIsValidCashBillEx(params: Omit<CheckIsValidCashBillEx, 'CERTKEY' | 'CorpNum'>): Promise<CheckIsValidCashBillExResponse> {
    return this.call<CheckIsValidCashBillExResponse>('CheckIsValidCashBillEx', params);
  }

  async registCashBill(params: Omit<RegistCashBill, 'CERTKEY' | 'CorpNum'>): Promise<RegistCashBillResponse> {
    return this.call<RegistCashBillResponse>('RegistCashBill', params);
  }

  async registCashBillEx(params: Omit<RegistCashBillEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistCashBillExResponse> {
    return this.call<RegistCashBillExResponse>('RegistCashBillEx', params);
  }

  async updateCashBill(params: Omit<UpdateCashBill, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCashBillResponse> {
    return this.call<UpdateCashBillResponse>('UpdateCashBill', params);
  }

  async updateCashBillEx(params: Omit<UpdateCashBillEx, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCashBillExResponse> {
    return this.call<UpdateCashBillExResponse>('UpdateCashBillEx', params);
  }

  async deleteCashBill(params: Omit<DeleteCashBill, 'CERTKEY' | 'CorpNum'>): Promise<DeleteCashBillResponse> {
    return this.call<DeleteCashBillResponse>('DeleteCashBill', params);
  }

  async issueCashBill(params: Omit<IssueCashBill, 'CERTKEY' | 'CorpNum'>): Promise<IssueCashBillResponse> {
    return this.call<IssueCashBillResponse>('IssueCashBill', params);
  }

  async cancelCashBill(params: Omit<CancelCashBill, 'CERTKEY' | 'CorpNum'>): Promise<CancelCashBillResponse> {
    return this.call<CancelCashBillResponse>('CancelCashBill', params);
  }

  async cancelCashBillPartial(params: Omit<CancelCashBillPartial, 'CERTKEY' | 'CorpNum'>): Promise<CancelCashBillPartialResponse> {
    return this.call<CancelCashBillPartialResponse>('CancelCashBillPartial', params);
  }

  async cancelCashBillEx(params: Omit<CancelCashBillEx, 'CERTKEY' | 'CorpNum'>): Promise<CancelCashBillExResponse> {
    return this.call<CancelCashBillExResponse>('CancelCashBillEx', params);
  }

  async cancelCashBillPartialEx(params: Omit<CancelCashBillPartialEx, 'CERTKEY' | 'CorpNum'>): Promise<CancelCashBillPartialExResponse> {
    return this.call<CancelCashBillPartialExResponse>('CancelCashBillPartialEx', params);
  }

  async cancelCashBillBeforeNTSSend(params: Omit<CancelCashBillBeforeNtsSend, 'CERTKEY' | 'CorpNum'>): Promise<CancelCashBillBeforeNtsSendResponse> {
    return this.call<CancelCashBillBeforeNtsSendResponse>('CancelCashBillBeforeNTSSend', params);
  }

  async getCancelableAmount(params: Omit<GetCancelableAmount, 'CERTKEY' | 'CorpNum'>): Promise<GetCancelableAmountResponse> {
    return this.call<GetCancelableAmountResponse>('GetCancelableAmount', params);
  }

  async registAndIssueCashBill(params: Omit<RegistAndIssueCashBill, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndIssueCashBillResponse> {
    return this.call<RegistAndIssueCashBillResponse>('RegistAndIssueCashBill', params);
  }

  async getCashBill(params: Omit<GetCashBill, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillResponse> {
    return this.call<GetCashBillResponse>('GetCashBill', params);
  }

  async getCashBillEx(params: Omit<GetCashBillEx, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillExResponse> {
    return this.call<GetCashBillExResponse>('GetCashBillEx', params);
  }

  async getCashBillExNK(params: Omit<GetCashBillExNk, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillExNkResponse> {
    return this.call<GetCashBillExNkResponse>('GetCashBillExNK', params);
  }

  async getCashBillState(params: Omit<GetCashBillState, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillStateResponse> {
    return this.call<GetCashBillStateResponse>('GetCashBillState', params);
  }

  async getCashBillStates(params: Omit<GetCashBillStates, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillStatesResponse> {
    return this.call<GetCashBillStatesResponse>('GetCashBillStates', params);
  }

  async getCashBillLog(params: Omit<GetCashBillLog, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillLogResponse> {
    return this.call<GetCashBillLogResponse>('GetCashBillLog', params);
  }

  async getCancelCashBills(params: Omit<GetCancelCashBills, 'CERTKEY' | 'CorpNum'>): Promise<GetCancelCashBillsResponse> {
    return this.call<GetCancelCashBillsResponse>('GetCancelCashBills', params);
  }

  async sendEmailEx(params: Omit<SendEmailEx, 'CERTKEY' | 'CorpNum'>): Promise<SendEmailExResponse> {
    return this.call<SendEmailExResponse>('SendEmailEx', params);
  }

  async sendMessageEx(params: Omit<SendMessageEx, 'CERTKEY' | 'CorpNum'>): Promise<SendMessageExResponse> {
    return this.call<SendMessageExResponse>('SendMessageEx', params);
  }

  async sendFaxEx(params: Omit<SendFaxEx, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxExResponse> {
    return this.call<SendFaxExResponse>('SendFaxEx', params);
  }

  async sendEmail(params: Omit<SendEmail, 'CERTKEY' | 'CorpNum'>): Promise<SendEmailResponse> {
    return this.call<SendEmailResponse>('SendEmail', params);
  }

  async sendSMS(params: Omit<SendSms, 'CERTKEY' | 'CorpNum'>): Promise<SendSmsResponse> {
    return this.call<SendSmsResponse>('SendSMS', params);
  }

  async sendFax(params: Omit<SendFax, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxResponse> {
    return this.call<SendFaxResponse>('SendFax', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getCashBillPopUpURL(params: Omit<GetCashBillPopUpUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPopUpUrlResponse> {
    return this.call<GetCashBillPopUpUrlResponse>('GetCashBillPopUpURL', params);
  }

  async getCashBillPopUpURLNK(params: Omit<GetCashBillPopUpUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPopUpUrlnkResponse> {
    return this.call<GetCashBillPopUpUrlnkResponse>('GetCashBillPopUpURLNK', params);
  }

  async getCashBillPrintURL(params: Omit<GetCashBillPrintUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPrintUrlResponse> {
    return this.call<GetCashBillPrintUrlResponse>('GetCashBillPrintURL', params);
  }

  async getCashBillPrintURLNK(params: Omit<GetCashBillPrintUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPrintUrlnkResponse> {
    return this.call<GetCashBillPrintUrlnkResponse>('GetCashBillPrintURLNK', params);
  }

  async getCashBillsPrintURL(params: Omit<GetCashBillsPrintUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillsPrintUrlResponse> {
    return this.call<GetCashBillsPrintUrlResponse>('GetCashBillsPrintURL', params);
  }

  async getCashBillMailURL(params: Omit<GetCashBillMailUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillMailUrlResponse> {
    return this.call<GetCashBillMailUrlResponse>('GetCashBillMailURL', params);
  }

  async getCashBillMailURLNK(params: Omit<GetCashBillMailUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillMailUrlnkResponse> {
    return this.call<GetCashBillMailUrlnkResponse>('GetCashBillMailURLNK', params);
  }

  async getCashBillSalesList(params: Omit<GetCashBillSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillSalesListResponse> {
    return this.call<GetCashBillSalesListResponse>('GetCashBillSalesList', params);
  }

  async getCashBillSalesListEx(params: Omit<GetCashBillSalesListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillSalesListExResponse> {
    return this.call<GetCashBillSalesListExResponse>('GetCashBillSalesListEx', params);
  }

  async getCashBillPurchaseList(params: Omit<GetCashBillPurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPurchaseListResponse> {
    return this.call<GetCashBillPurchaseListResponse>('GetCashBillPurchaseList', params);
  }

  async getCashBillPurchaseListEx(params: Omit<GetCashBillPurchaseListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPurchaseListExResponse> {
    return this.call<GetCashBillPurchaseListExResponse>('GetCashBillPurchaseListEx', params);
  }

  async getDailyCashBillSalesList(params: Omit<GetDailyCashBillSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyCashBillSalesListResponse> {
    return this.call<GetDailyCashBillSalesListResponse>('GetDailyCashBillSalesList', params);
  }

  async getDailyCashBillSalesListEx(params: Omit<GetDailyCashBillSalesListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyCashBillSalesListExResponse> {
    return this.call<GetDailyCashBillSalesListExResponse>('GetDailyCashBillSalesListEx', params);
  }

  async getDailyCashBillPurchaseList(params: Omit<GetDailyCashBillPurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyCashBillPurchaseListResponse> {
    return this.call<GetDailyCashBillPurchaseListResponse>('GetDailyCashBillPurchaseList', params);
  }

  async getDailyCashBillPurchaseListEx(params: Omit<GetDailyCashBillPurchaseListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyCashBillPurchaseListExResponse> {
    return this.call<GetDailyCashBillPurchaseListExResponse>('GetDailyCashBillPurchaseListEx', params);
  }

  async getMonthlyCashBillSalesList(params: Omit<GetMonthlyCashBillSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyCashBillSalesListResponse> {
    return this.call<GetMonthlyCashBillSalesListResponse>('GetMonthlyCashBillSalesList', params);
  }

  async getMonthlyCashBillSalesListEx(params: Omit<GetMonthlyCashBillSalesListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyCashBillSalesListExResponse> {
    return this.call<GetMonthlyCashBillSalesListExResponse>('GetMonthlyCashBillSalesListEx', params);
  }

  async getMonthlyCashBillPurchaseList(params: Omit<GetMonthlyCashBillPurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyCashBillPurchaseListResponse> {
    return this.call<GetMonthlyCashBillPurchaseListResponse>('GetMonthlyCashBillPurchaseList', params);
  }

  async getMonthlyCashBillPurchaseListEx(params: Omit<GetMonthlyCashBillPurchaseListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyCashBillPurchaseListExResponse> {
    return this.call<GetMonthlyCashBillPurchaseListExResponse>('GetMonthlyCashBillPurchaseListEx', params);
  }

  async getPeriodCashBillSalesList(params: Omit<GetPeriodCashBillSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodCashBillSalesListResponse> {
    return this.call<GetPeriodCashBillSalesListResponse>('GetPeriodCashBillSalesList', params);
  }

  async getPeriodCashBillSalesListEx(params: Omit<GetPeriodCashBillSalesListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodCashBillSalesListExResponse> {
    return this.call<GetPeriodCashBillSalesListExResponse>('GetPeriodCashBillSalesListEx', params);
  }

  async getPeriodCashBillPurchaseList(params: Omit<GetPeriodCashBillPurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodCashBillPurchaseListResponse> {
    return this.call<GetPeriodCashBillPurchaseListResponse>('GetPeriodCashBillPurchaseList', params);
  }

  async getPeriodCashBillPurchaseListEx(params: Omit<GetPeriodCashBillPurchaseListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodCashBillPurchaseListExResponse> {
    return this.call<GetPeriodCashBillPurchaseListExResponse>('GetPeriodCashBillPurchaseListEx', params);
  }

  async getCashBillSalesListByID(params: Omit<GetCashBillSalesListById, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillSalesListByIdResponse> {
    return this.call<GetCashBillSalesListByIdResponse>('GetCashBillSalesListByID', params);
  }

  async getCashBillPurchaseListByID(params: Omit<GetCashBillPurchaseListById, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillPurchaseListByIdResponse> {
    return this.call<GetCashBillPurchaseListByIdResponse>('GetCashBillPurchaseListByID', params);
  }

  async registCashBillScrap(params: Omit<RegistCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<RegistCashBillScrapResponse> {
    return this.call<RegistCashBillScrapResponse>('RegistCashBillScrap', params);
  }

  async registCashBillScrapEx(params: Omit<RegistCashBillScrapEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistCashBillScrapExResponse> {
    return this.call<RegistCashBillScrapExResponse>('RegistCashBillScrapEx', params);
  }

  async updateCashBillScrap(params: Omit<UpdateCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCashBillScrapResponse> {
    return this.call<UpdateCashBillScrapResponse>('UpdateCashBillScrap', params);
  }

  async updateCashBillScrapEx(params: Omit<UpdateCashBillScrapEx, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCashBillScrapExResponse> {
    return this.call<UpdateCashBillScrapExResponse>('UpdateCashBillScrapEx', params);
  }

  async stopCashBillScrap(params: Omit<StopCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<StopCashBillScrapResponse> {
    return this.call<StopCashBillScrapResponse>('StopCashBillScrap', params);
  }

  async cancelStopCashBillScrap(params: Omit<CancelStopCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<CancelStopCashBillScrapResponse> {
    return this.call<CancelStopCashBillScrapResponse>('CancelStopCashBillScrap', params);
  }

  async reRegistCashBillScrap(params: Omit<ReRegistCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<ReRegistCashBillScrapResponse> {
    return this.call<ReRegistCashBillScrapResponse>('ReRegistCashBillScrap', params);
  }

  async getCashBillScrapRequestURL(params: Omit<GetCashBillScrapRequestUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashBillScrapRequestUrlResponse> {
    return this.call<GetCashBillScrapRequestUrlResponse>('GetCashBillScrapRequestURL', params);
  }

  async refreshCashBillScrap(params: Omit<RefreshCashBillScrap, 'CERTKEY' | 'CorpNum'>): Promise<RefreshCashBillScrapResponse> {
    return this.call<RefreshCashBillScrapResponse>('RefreshCashBillScrap', params);
  }

  async makeDocLinkage(params: Omit<MakeDocLinkage, 'CERTKEY' | 'CorpNum'>): Promise<MakeDocLinkageResponse> {
    return this.call<MakeDocLinkageResponse>('MakeDocLinkage', params);
  }

  async removeDocLinkage(params: Omit<RemoveDocLinkage, 'CERTKEY' | 'CorpNum'>): Promise<RemoveDocLinkageResponse> {
    return this.call<RemoveDocLinkageResponse>('RemoveDocLinkage', params);
  }

  async getLinkedDocs(params: Omit<GetLinkedDocs, 'CERTKEY' | 'CorpNum'>): Promise<GetLinkedDocsResponse> {
    return this.call<GetLinkedDocsResponse>('GetLinkedDocs', params);
  }

  async getJicInRegistURL(params: Omit<GetJicInRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetJicInRegistUrlResponse> {
    return this.call<GetJicInRegistUrlResponse>('GetJicInRegistURL', params);
  }

  async getBusinessLicenseRegistURL(params: Omit<GetBusinessLicenseRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBusinessLicenseRegistUrlResponse> {
    return this.call<GetBusinessLicenseRegistUrlResponse>('GetBusinessLicenseRegistURL', params);
  }

  async getBankBookRegistURL(params: Omit<GetBankBookRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBankBookRegistUrlResponse> {
    return this.call<GetBankBookRegistUrlResponse>('GetBankBookRegistURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY' | 'CorpNum'>): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY' | 'CorpNum'>): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY' | 'CorpNum'>): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY' | 'CorpNum'>): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY' | 'CorpNum'>): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY' | 'CorpNum'>): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY' | 'CorpNum'>): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
