// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { CheckMgtNumIsExists } from './generated/definitions/CheckMgtNumIsExists';
import type { CheckMgtNumIsExistsResponse } from './generated/definitions/CheckMgtNumIsExistsResponse';
import type { CheckIsValidTaxInvoice } from './generated/definitions/CheckIsValidTaxInvoice';
import type { CheckIsValidTaxInvoiceResponse } from './generated/definitions/CheckIsValidTaxInvoiceResponse';
import type { RegistTaxInvoice } from './generated/definitions/RegistTaxInvoice';
import type { RegistTaxInvoiceResponse } from './generated/definitions/RegistTaxInvoiceResponse';
import type { RegistTaxInvoiceEx } from './generated/definitions/RegistTaxInvoiceEx';
import type { RegistTaxInvoiceExResponse } from './generated/definitions/RegistTaxInvoiceExResponse';
import type { RegistModifyTaxInvoice } from './generated/definitions/RegistModifyTaxInvoice';
import type { RegistModifyTaxInvoiceResponse } from './generated/definitions/RegistModifyTaxInvoiceResponse';
import type { RegistModifyTaxInvoiceEx } from './generated/definitions/RegistModifyTaxInvoiceEx';
import type { RegistModifyTaxInvoiceExResponse } from './generated/definitions/RegistModifyTaxInvoiceExResponse';
import type { RegistTaxInvoiceReverse } from './generated/definitions/RegistTaxInvoiceReverse';
import type { RegistTaxInvoiceReverseResponse } from './generated/definitions/RegistTaxInvoiceReverseResponse';
import type { RegistTaxInvoiceReverseEx } from './generated/definitions/RegistTaxInvoiceReverseEx';
import type { RegistTaxInvoiceReverseExResponse } from './generated/definitions/RegistTaxInvoiceReverseExResponse';
import type { RegistBrokerTaxInvoice } from './generated/definitions/RegistBrokerTaxInvoice';
import type { RegistBrokerTaxInvoiceResponse } from './generated/definitions/RegistBrokerTaxInvoiceResponse';
import type { RegistBrokerTaxInvoiceEx } from './generated/definitions/RegistBrokerTaxInvoiceEx';
import type { RegistBrokerTaxInvoiceExResponse } from './generated/definitions/RegistBrokerTaxInvoiceExResponse';
import type { RegistModifyBrokerTaxInvoice } from './generated/definitions/RegistModifyBrokerTaxInvoice';
import type { RegistModifyBrokerTaxInvoiceResponse } from './generated/definitions/RegistModifyBrokerTaxInvoiceResponse';
import type { RegistModifyBrokerTaxInvoiceEx } from './generated/definitions/RegistModifyBrokerTaxInvoiceEx';
import type { RegistModifyBrokerTaxInvoiceExResponse } from './generated/definitions/RegistModifyBrokerTaxInvoiceExResponse';
import type { UpdateTaxInvoice } from './generated/definitions/UpdateTaxInvoice';
import type { UpdateTaxInvoiceResponse } from './generated/definitions/UpdateTaxInvoiceResponse';
import type { UpdateTaxInvoiceEx } from './generated/definitions/UpdateTaxInvoiceEx';
import type { UpdateTaxInvoiceExResponse } from './generated/definitions/UpdateTaxInvoiceExResponse';
import type { UpdateBrokerTaxInvoice } from './generated/definitions/UpdateBrokerTaxInvoice';
import type { UpdateBrokerTaxInvoiceResponse } from './generated/definitions/UpdateBrokerTaxInvoiceResponse';
import type { UpdateBrokerTaxInvoiceEx } from './generated/definitions/UpdateBrokerTaxInvoiceEx';
import type { UpdateBrokerTaxInvoiceExResponse } from './generated/definitions/UpdateBrokerTaxInvoiceExResponse';
import type { UpdateTaxInvoiceFooterString } from './generated/definitions/UpdateTaxInvoiceFooterString';
import type { UpdateTaxInvoiceFooterStringResponse } from './generated/definitions/UpdateTaxInvoiceFooterStringResponse';
import type { DeleteTaxInvoice } from './generated/definitions/DeleteTaxInvoice';
import type { DeleteTaxInvoiceResponse } from './generated/definitions/DeleteTaxInvoiceResponse';
import type { DeleteTaxInvoiceIk } from './generated/definitions/DeleteTaxInvoiceIk';
import type { DeleteTaxInvoiceIkResponse } from './generated/definitions/DeleteTaxInvoiceIkResponse';
import type { IssueTaxInvoice } from './generated/definitions/IssueTaxInvoice';
import type { IssueTaxInvoiceResponse } from './generated/definitions/IssueTaxInvoiceResponse';
import type { IssueTaxInvoiceEx } from './generated/definitions/IssueTaxInvoiceEx';
import type { IssueTaxInvoiceExResponse } from './generated/definitions/IssueTaxInvoiceExResponse';
import type { ReverseIssueTaxInvoice } from './generated/definitions/ReverseIssueTaxInvoice';
import type { ReverseIssueTaxInvoiceResponse } from './generated/definitions/ReverseIssueTaxInvoiceResponse';
import type { ReverseIssueTaxInvoiceEx } from './generated/definitions/ReverseIssueTaxInvoiceEx';
import type { ReverseIssueTaxInvoiceExResponse } from './generated/definitions/ReverseIssueTaxInvoiceExResponse';
import type { PreIssueTaxInvoice } from './generated/definitions/PreIssueTaxInvoice';
import type { PreIssueTaxInvoiceResponse } from './generated/definitions/PreIssueTaxInvoiceResponse';
import type { PreIssueTaxInvoiceEx } from './generated/definitions/PreIssueTaxInvoiceEx';
import type { PreIssueTaxInvoiceExResponse } from './generated/definitions/PreIssueTaxInvoiceExResponse';
import type { ProcTaxInvoice } from './generated/definitions/ProcTaxInvoice';
import type { ProcTaxInvoiceResponse } from './generated/definitions/ProcTaxInvoiceResponse';
import type { RegistAndIssueTaxInvoice } from './generated/definitions/RegistAndIssueTaxInvoice';
import type { RegistAndIssueTaxInvoiceResponse } from './generated/definitions/RegistAndIssueTaxInvoiceResponse';
import type { RegistAndPreIssueTaxInvoice } from './generated/definitions/RegistAndPreIssueTaxInvoice';
import type { RegistAndPreIssueTaxInvoiceResponse } from './generated/definitions/RegistAndPreIssueTaxInvoiceResponse';
import type { RegistAndIssueBrokerTaxInvoice } from './generated/definitions/RegistAndIssueBrokerTaxInvoice';
import type { RegistAndIssueBrokerTaxInvoiceResponse } from './generated/definitions/RegistAndIssueBrokerTaxInvoiceResponse';
import type { RegistAndPreIssueBrokerTaxInvoice } from './generated/definitions/RegistAndPreIssueBrokerTaxInvoice';
import type { RegistAndPreIssueBrokerTaxInvoiceResponse } from './generated/definitions/RegistAndPreIssueBrokerTaxInvoiceResponse';
import type { RegistAndReverseIssueTaxInvoice } from './generated/definitions/RegistAndReverseIssueTaxInvoice';
import type { RegistAndReverseIssueTaxInvoiceResponse } from './generated/definitions/RegistAndReverseIssueTaxInvoiceResponse';
import type { RegistAndIssueTaxInvoiceBulk } from './generated/definitions/RegistAndIssueTaxInvoiceBulk';
import type { RegistAndIssueTaxInvoiceBulkResponse } from './generated/definitions/RegistAndIssueTaxInvoiceBulkResponse';
import type { RegistAndPreIssueTaxInvoiceBulk } from './generated/definitions/RegistAndPreIssueTaxInvoiceBulk';
import type { RegistAndPreIssueTaxInvoiceBulkResponse } from './generated/definitions/RegistAndPreIssueTaxInvoiceBulkResponse';
import type { RegistAndIssueBrokerTaxInvoiceBulk } from './generated/definitions/RegistAndIssueBrokerTaxInvoiceBulk';
import type { RegistAndIssueBrokerTaxInvoiceBulkResponse } from './generated/definitions/RegistAndIssueBrokerTaxInvoiceBulkResponse';
import type { RegistAndPreIssueBrokerTaxInvoiceBulk } from './generated/definitions/RegistAndPreIssueBrokerTaxInvoiceBulk';
import type { RegistAndPreIssueBrokerTaxInvoiceBulkResponse } from './generated/definitions/RegistAndPreIssueBrokerTaxInvoiceBulkResponse';
import type { RegistAndReverseIssueTaxInvoiceBulk } from './generated/definitions/RegistAndReverseIssueTaxInvoiceBulk';
import type { RegistAndReverseIssueTaxInvoiceBulkResponse } from './generated/definitions/RegistAndReverseIssueTaxInvoiceBulkResponse';
import type { GetTaxInvoice } from './generated/definitions/GetTaxInvoice';
import type { GetTaxInvoiceResponse } from './generated/definitions/GetTaxInvoiceResponse';
import type { GetTaxInvoiceIk } from './generated/definitions/GetTaxInvoiceIk';
import type { GetTaxInvoiceIkResponse } from './generated/definitions/GetTaxInvoiceIkResponse';
import type { GetTaxInvoiceNk } from './generated/definitions/GetTaxInvoiceNk';
import type { GetTaxInvoiceNkResponse } from './generated/definitions/GetTaxInvoiceNkResponse';
import type { GetTaxInvoiceState } from './generated/definitions/GetTaxInvoiceState';
import type { GetTaxInvoiceStateResponse } from './generated/definitions/GetTaxInvoiceStateResponse';
import type { GetTaxInvoiceStates } from './generated/definitions/GetTaxInvoiceStates';
import type { GetTaxInvoiceStatesResponse } from './generated/definitions/GetTaxInvoiceStatesResponse';
import type { GetTaxInvoiceStateEx } from './generated/definitions/GetTaxInvoiceStateEx';
import type { GetTaxInvoiceStateExResponse } from './generated/definitions/GetTaxInvoiceStateExResponse';
import type { GetTaxInvoiceStatesEx } from './generated/definitions/GetTaxInvoiceStatesEx';
import type { GetTaxInvoiceStatesExResponse } from './generated/definitions/GetTaxInvoiceStatesExResponse';
import type { GetTaxInvoiceStatesIk } from './generated/definitions/GetTaxInvoiceStatesIk';
import type { GetTaxInvoiceStatesIkResponse } from './generated/definitions/GetTaxInvoiceStatesIkResponse';
import type { GetTaxInvoiceLog } from './generated/definitions/GetTaxInvoiceLog';
import type { GetTaxInvoiceLogResponse } from './generated/definitions/GetTaxInvoiceLogResponse';
import type { GetTaxInvoiceLogIk } from './generated/definitions/GetTaxInvoiceLogIk';
import type { GetTaxInvoiceLogIkResponse } from './generated/definitions/GetTaxInvoiceLogIkResponse';
import type { AttachFileByFtp } from './generated/definitions/AttachFileByFtp';
import type { AttachFileByFtpResponse } from './generated/definitions/AttachFileByFtpResponse';
import type { AttachFilesByFtp } from './generated/definitions/AttachFilesByFtp';
import type { AttachFilesByFtpResponse } from './generated/definitions/AttachFilesByFtpResponse';
import type { DeleteAttachFile } from './generated/definitions/DeleteAttachFile';
import type { DeleteAttachFileResponse } from './generated/definitions/DeleteAttachFileResponse';
import type { DeleteAttachFileWithFileIndex } from './generated/definitions/DeleteAttachFileWithFileIndex';
import type { DeleteAttachFileWithFileIndexResponse } from './generated/definitions/DeleteAttachFileWithFileIndexResponse';
import type { GetAttachedFileList } from './generated/definitions/GetAttachedFileList';
import type { GetAttachedFileListResponse } from './generated/definitions/GetAttachedFileListResponse';
import type { GetAttachedFileListEx } from './generated/definitions/GetAttachedFileListEx';
import type { GetAttachedFileListExResponse } from './generated/definitions/GetAttachedFileListExResponse';
import type { SendEmailEx } from './generated/definitions/SendEmailEx';
import type { SendEmailExResponse } from './generated/definitions/SendEmailExResponse';
import type { SendEmailToTruster } from './generated/definitions/SendEmailToTruster';
import type { SendEmailToTrusterResponse } from './generated/definitions/SendEmailToTrusterResponse';
import type { SendMessageEx } from './generated/definitions/SendMessageEx';
import type { SendMessageExResponse } from './generated/definitions/SendMessageExResponse';
import type { SendFaxEx } from './generated/definitions/SendFaxEx';
import type { SendFaxExResponse } from './generated/definitions/SendFaxExResponse';
import type { ReSendEmail } from './generated/definitions/ReSendEmail';
import type { ReSendEmailResponse } from './generated/definitions/ReSendEmailResponse';
import type { ReSendSms } from './generated/definitions/ReSendSms';
import type { ReSendSmsResponse } from './generated/definitions/ReSendSmsResponse';
import type { SendInvoiceSms } from './generated/definitions/SendInvoiceSms';
import type { SendInvoiceSmsResponse } from './generated/definitions/SendInvoiceSmsResponse';
import type { SendInvoiceFax } from './generated/definitions/SendInvoiceFax';
import type { SendInvoiceFaxResponse } from './generated/definitions/SendInvoiceFaxResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetTaxInvoicePopUpUrl } from './generated/definitions/GetTaxInvoicePopUpUrl';
import type { GetTaxInvoicePopUpUrlResponse } from './generated/definitions/GetTaxInvoicePopUpUrlResponse';
import type { GetTaxInvoicePopUpUrlik } from './generated/definitions/GetTaxInvoicePopUpUrlik';
import type { GetTaxInvoicePopUpUrlikResponse } from './generated/definitions/GetTaxInvoicePopUpUrlikResponse';
import type { GetTaxInvoicePopUpUrlnk } from './generated/definitions/GetTaxInvoicePopUpUrlnk';
import type { GetTaxInvoicePopUpUrlnkResponse } from './generated/definitions/GetTaxInvoicePopUpUrlnkResponse';
import type { GetTaxInvoicePrintUrl } from './generated/definitions/GetTaxInvoicePrintUrl';
import type { GetTaxInvoicePrintUrlResponse } from './generated/definitions/GetTaxInvoicePrintUrlResponse';
import type { GetTaxInvoicePrintUrlik } from './generated/definitions/GetTaxInvoicePrintUrlik';
import type { GetTaxInvoicePrintUrlikResponse } from './generated/definitions/GetTaxInvoicePrintUrlikResponse';
import type { GetTaxInvoicePrintUrlnk } from './generated/definitions/GetTaxInvoicePrintUrlnk';
import type { GetTaxInvoicePrintUrlnkResponse } from './generated/definitions/GetTaxInvoicePrintUrlnkResponse';
import type { GetTaxInvoicesPrintUrl } from './generated/definitions/GetTaxInvoicesPrintUrl';
import type { GetTaxInvoicesPrintUrlResponse } from './generated/definitions/GetTaxInvoicesPrintUrlResponse';
import type { GetTaxInvoicesPrintUrlnk } from './generated/definitions/GetTaxInvoicesPrintUrlnk';
import type { GetTaxInvoicesPrintUrlnkResponse } from './generated/definitions/GetTaxInvoicesPrintUrlnkResponse';
import type { GetTaxinvoiceMailUrl } from './generated/definitions/GetTaxinvoiceMailUrl';
import type { GetTaxinvoiceMailUrlResponse } from './generated/definitions/GetTaxinvoiceMailUrlResponse';
import type { GetTaxInvoiceMailUrlnk } from './generated/definitions/GetTaxInvoiceMailUrlnk';
import type { GetTaxInvoiceMailUrlnkResponse } from './generated/definitions/GetTaxInvoiceMailUrlnkResponse';
import type { GetTaxInvoiceSalesList } from './generated/definitions/GetTaxInvoiceSalesList';
import type { GetTaxInvoiceSalesListResponse } from './generated/definitions/GetTaxInvoiceSalesListResponse';
import type { GetTaxInvoiceSalesListEx } from './generated/definitions/GetTaxInvoiceSalesListEx';
import type { GetTaxInvoiceSalesListExResponse } from './generated/definitions/GetTaxInvoiceSalesListExResponse';
import type { GetTaxInvoicePurchaseList } from './generated/definitions/GetTaxInvoicePurchaseList';
import type { GetTaxInvoicePurchaseListResponse } from './generated/definitions/GetTaxInvoicePurchaseListResponse';
import type { GetTaxInvoicePurchaseListEx } from './generated/definitions/GetTaxInvoicePurchaseListEx';
import type { GetTaxInvoicePurchaseListExResponse } from './generated/definitions/GetTaxInvoicePurchaseListExResponse';
import type { GetDailyTaxInvoiceSalesList } from './generated/definitions/GetDailyTaxInvoiceSalesList';
import type { GetDailyTaxInvoiceSalesListResponse } from './generated/definitions/GetDailyTaxInvoiceSalesListResponse';
import type { GetDailyTaxInvoicePurchaseList } from './generated/definitions/GetDailyTaxInvoicePurchaseList';
import type { GetDailyTaxInvoicePurchaseListResponse } from './generated/definitions/GetDailyTaxInvoicePurchaseListResponse';
import type { GetMonthlyTaxInvoiceSalesList } from './generated/definitions/GetMonthlyTaxInvoiceSalesList';
import type { GetMonthlyTaxInvoiceSalesListResponse } from './generated/definitions/GetMonthlyTaxInvoiceSalesListResponse';
import type { GetMonthlyTaxInvoicePurchaseList } from './generated/definitions/GetMonthlyTaxInvoicePurchaseList';
import type { GetMonthlyTaxInvoicePurchaseListResponse } from './generated/definitions/GetMonthlyTaxInvoicePurchaseListResponse';
import type { GetPeriodTaxInvoiceSalesList } from './generated/definitions/GetPeriodTaxInvoiceSalesList';
import type { GetPeriodTaxInvoiceSalesListResponse } from './generated/definitions/GetPeriodTaxInvoiceSalesListResponse';
import type { GetPeriodTaxInvoicePurchaseList } from './generated/definitions/GetPeriodTaxInvoicePurchaseList';
import type { GetPeriodTaxInvoicePurchaseListResponse } from './generated/definitions/GetPeriodTaxInvoicePurchaseListResponse';
import type { GetMonthlyCountTaxInvoice } from './generated/definitions/GetMonthlyCountTaxInvoice';
import type { GetMonthlyCountTaxInvoiceResponse } from './generated/definitions/GetMonthlyCountTaxInvoiceResponse';
import type { GetCanceledTaxInvoiceMgtKey } from './generated/definitions/GetCanceledTaxInvoiceMgtKey';
import type { GetCanceledTaxInvoiceMgtKeyResponse } from './generated/definitions/GetCanceledTaxInvoiceMgtKeyResponse';
import type { GetTaxInvoiceSalesListById } from './generated/definitions/GetTaxInvoiceSalesListById';
import type { GetTaxInvoiceSalesListByIdResponse } from './generated/definitions/GetTaxInvoiceSalesListByIdResponse';
import type { GetTaxInvoicePurchaseListById } from './generated/definitions/GetTaxInvoicePurchaseListById';
import type { GetTaxInvoicePurchaseListByIdResponse } from './generated/definitions/GetTaxInvoicePurchaseListByIdResponse';
import type { GetTaxInvoiceSalesListByIdEx } from './generated/definitions/GetTaxInvoiceSalesListByIdEx';
import type { GetTaxInvoiceSalesListByIdExResponse } from './generated/definitions/GetTaxInvoiceSalesListByIdExResponse';
import type { GetTaxInvoicePurchaseListByIdEx } from './generated/definitions/GetTaxInvoicePurchaseListByIdEx';
import type { GetTaxInvoicePurchaseListByIdExResponse } from './generated/definitions/GetTaxInvoicePurchaseListByIdExResponse';
import type { SendToNts } from './generated/definitions/SendToNts';
import type { SendToNtsResponse } from './generated/definitions/SendToNtsResponse';
import type { GetNtsSendOption } from './generated/definitions/GetNtsSendOption';
import type { GetNtsSendOptionResponse } from './generated/definitions/GetNtsSendOptionResponse';
import type { ChangeNtsSendOption } from './generated/definitions/ChangeNtsSendOption';
import type { ChangeNtsSendOptionResponse } from './generated/definitions/ChangeNtsSendOptionResponse';
import type { GetEmailPublicKeys } from './generated/definitions/GetEmailPublicKeys';
import type { GetEmailPublicKeysResponse } from './generated/definitions/GetEmailPublicKeysResponse';
import type { RegistTaxInvoiceScrap } from './generated/definitions/RegistTaxInvoiceScrap';
import type { RegistTaxInvoiceScrapResponse } from './generated/definitions/RegistTaxInvoiceScrapResponse';
import type { RegistTaxInvoiceScrapEx } from './generated/definitions/RegistTaxInvoiceScrapEx';
import type { RegistTaxInvoiceScrapExResponse } from './generated/definitions/RegistTaxInvoiceScrapExResponse';
import type { UpdateTaxInvoiceScrap } from './generated/definitions/UpdateTaxInvoiceScrap';
import type { UpdateTaxInvoiceScrapResponse } from './generated/definitions/UpdateTaxInvoiceScrapResponse';
import type { UpdateTaxInvoiceScrapEx } from './generated/definitions/UpdateTaxInvoiceScrapEx';
import type { UpdateTaxInvoiceScrapExResponse } from './generated/definitions/UpdateTaxInvoiceScrapExResponse';
import type { StopTaxInvoiceScrap } from './generated/definitions/StopTaxInvoiceScrap';
import type { StopTaxInvoiceScrapResponse } from './generated/definitions/StopTaxInvoiceScrapResponse';
import type { CancelStopTaxInvoiceScrap } from './generated/definitions/CancelStopTaxInvoiceScrap';
import type { CancelStopTaxInvoiceScrapResponse } from './generated/definitions/CancelStopTaxInvoiceScrapResponse';
import type { ReRegistTaxInvoiceScrap } from './generated/definitions/ReRegistTaxInvoiceScrap';
import type { ReRegistTaxInvoiceScrapResponse } from './generated/definitions/ReRegistTaxInvoiceScrapResponse';
import type { GetTaxInvoiceScrapRequestUrl } from './generated/definitions/GetTaxInvoiceScrapRequestUrl';
import type { GetTaxInvoiceScrapRequestUrlResponse } from './generated/definitions/GetTaxInvoiceScrapRequestUrlResponse';
import type { RefreshTaxInvoiceScrap } from './generated/definitions/RefreshTaxInvoiceScrap';
import type { RefreshTaxInvoiceScrapResponse } from './generated/definitions/RefreshTaxInvoiceScrapResponse';
import type { MakeDocLinkage } from './generated/definitions/MakeDocLinkage';
import type { MakeDocLinkageResponse } from './generated/definitions/MakeDocLinkageResponse';
import type { RemoveDocLinkage } from './generated/definitions/RemoveDocLinkage';
import type { RemoveDocLinkageResponse } from './generated/definitions/RemoveDocLinkageResponse';
import type { GetLinkedDocs } from './generated/definitions/GetLinkedDocs';
import type { GetLinkedDocsResponse } from './generated/definitions/GetLinkedDocsResponse';
import type { GetJicInRegistUrl } from './generated/definitions/GetJicInRegistUrl';
import type { GetJicInRegistUrlResponse } from './generated/definitions/GetJicInRegistUrlResponse';
import type { GetBusinessLicenseRegistUrl } from './generated/definitions/GetBusinessLicenseRegistUrl';
import type { GetBusinessLicenseRegistUrlResponse } from './generated/definitions/GetBusinessLicenseRegistUrlResponse';
import type { GetBankBookRegistUrl } from './generated/definitions/GetBankBookRegistUrl';
import type { GetBankBookRegistUrlResponse } from './generated/definitions/GetBankBookRegistUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class TiClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'TI';
  }

  static async create(config: BarobillConfig): Promise<TiClient> {
    const client = new TiClient(config);
    await client.init();
    return client;
  }

  async checkMgtNumIsExists(params: Omit<CheckMgtNumIsExists, 'CERTKEY' | 'CorpNum'>): Promise<CheckMgtNumIsExistsResponse> {
    return this.call<CheckMgtNumIsExistsResponse>('CheckMgtNumIsExists', params);
  }

  async checkIsValidTaxInvoice(params: Omit<CheckIsValidTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<CheckIsValidTaxInvoiceResponse> {
    return this.call<CheckIsValidTaxInvoiceResponse>('CheckIsValidTaxInvoice', params);
  }

  async registTaxInvoice(params: Omit<RegistTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceResponse> {
    return this.call<RegistTaxInvoiceResponse>('RegistTaxInvoice', params);
  }

  async registTaxInvoiceEX(params: Omit<RegistTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceExResponse> {
    return this.call<RegistTaxInvoiceExResponse>('RegistTaxInvoiceEX', params);
  }

  async registModifyTaxInvoice(params: Omit<RegistModifyTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistModifyTaxInvoiceResponse> {
    return this.call<RegistModifyTaxInvoiceResponse>('RegistModifyTaxInvoice', params);
  }

  async registModifyTaxInvoiceEX(params: Omit<RegistModifyTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistModifyTaxInvoiceExResponse> {
    return this.call<RegistModifyTaxInvoiceExResponse>('RegistModifyTaxInvoiceEX', params);
  }

  async registTaxInvoiceReverse(params: Omit<RegistTaxInvoiceReverse, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceReverseResponse> {
    return this.call<RegistTaxInvoiceReverseResponse>('RegistTaxInvoiceReverse', params);
  }

  async registTaxInvoiceReverseEX(params: Omit<RegistTaxInvoiceReverseEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceReverseExResponse> {
    return this.call<RegistTaxInvoiceReverseExResponse>('RegistTaxInvoiceReverseEX', params);
  }

  async registBrokerTaxInvoice(params: Omit<RegistBrokerTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistBrokerTaxInvoiceResponse> {
    return this.call<RegistBrokerTaxInvoiceResponse>('RegistBrokerTaxInvoice', params);
  }

  async registBrokerTaxInvoiceEX(params: Omit<RegistBrokerTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistBrokerTaxInvoiceExResponse> {
    return this.call<RegistBrokerTaxInvoiceExResponse>('RegistBrokerTaxInvoiceEX', params);
  }

  async registModifyBrokerTaxInvoice(params: Omit<RegistModifyBrokerTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistModifyBrokerTaxInvoiceResponse> {
    return this.call<RegistModifyBrokerTaxInvoiceResponse>('RegistModifyBrokerTaxInvoice', params);
  }

  async registModifyBrokerTaxInvoiceEX(params: Omit<RegistModifyBrokerTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistModifyBrokerTaxInvoiceExResponse> {
    return this.call<RegistModifyBrokerTaxInvoiceExResponse>('RegistModifyBrokerTaxInvoiceEX', params);
  }

  async updateTaxInvoice(params: Omit<UpdateTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<UpdateTaxInvoiceResponse> {
    return this.call<UpdateTaxInvoiceResponse>('UpdateTaxInvoice', params);
  }

  async updateTaxInvoiceEX(params: Omit<UpdateTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<UpdateTaxInvoiceExResponse> {
    return this.call<UpdateTaxInvoiceExResponse>('UpdateTaxInvoiceEX', params);
  }

  async updateBrokerTaxInvoice(params: Omit<UpdateBrokerTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<UpdateBrokerTaxInvoiceResponse> {
    return this.call<UpdateBrokerTaxInvoiceResponse>('UpdateBrokerTaxInvoice', params);
  }

  async updateBrokerTaxInvoiceEX(params: Omit<UpdateBrokerTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<UpdateBrokerTaxInvoiceExResponse> {
    return this.call<UpdateBrokerTaxInvoiceExResponse>('UpdateBrokerTaxInvoiceEX', params);
  }

  async updateTaxInvoiceFooterString(params: Omit<UpdateTaxInvoiceFooterString, 'CERTKEY' | 'CorpNum'>): Promise<UpdateTaxInvoiceFooterStringResponse> {
    return this.call<UpdateTaxInvoiceFooterStringResponse>('UpdateTaxInvoiceFooterString', params);
  }

  async deleteTaxInvoice(params: Omit<DeleteTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<DeleteTaxInvoiceResponse> {
    return this.call<DeleteTaxInvoiceResponse>('DeleteTaxInvoice', params);
  }

  async deleteTaxInvoiceIK(params: Omit<DeleteTaxInvoiceIk, 'CERTKEY' | 'CorpNum'>): Promise<DeleteTaxInvoiceIkResponse> {
    return this.call<DeleteTaxInvoiceIkResponse>('DeleteTaxInvoiceIK', params);
  }

  async issueTaxInvoice(params: Omit<IssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<IssueTaxInvoiceResponse> {
    return this.call<IssueTaxInvoiceResponse>('IssueTaxInvoice', params);
  }

  async issueTaxInvoiceEx(params: Omit<IssueTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<IssueTaxInvoiceExResponse> {
    return this.call<IssueTaxInvoiceExResponse>('IssueTaxInvoiceEx', params);
  }

  async reverseIssueTaxInvoice(params: Omit<ReverseIssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<ReverseIssueTaxInvoiceResponse> {
    return this.call<ReverseIssueTaxInvoiceResponse>('ReverseIssueTaxInvoice', params);
  }

  async reverseIssueTaxInvoiceEx(params: Omit<ReverseIssueTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<ReverseIssueTaxInvoiceExResponse> {
    return this.call<ReverseIssueTaxInvoiceExResponse>('ReverseIssueTaxInvoiceEx', params);
  }

  async preIssueTaxInvoice(params: Omit<PreIssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<PreIssueTaxInvoiceResponse> {
    return this.call<PreIssueTaxInvoiceResponse>('PreIssueTaxInvoice', params);
  }

  async preIssueTaxInvoiceEx(params: Omit<PreIssueTaxInvoiceEx, 'CERTKEY' | 'CorpNum'>): Promise<PreIssueTaxInvoiceExResponse> {
    return this.call<PreIssueTaxInvoiceExResponse>('PreIssueTaxInvoiceEx', params);
  }

  async procTaxInvoice(params: Omit<ProcTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<ProcTaxInvoiceResponse> {
    return this.call<ProcTaxInvoiceResponse>('ProcTaxInvoice', params);
  }

  async registAndIssueTaxInvoice(params: Omit<RegistAndIssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndIssueTaxInvoiceResponse> {
    return this.call<RegistAndIssueTaxInvoiceResponse>('RegistAndIssueTaxInvoice', params);
  }

  async registAndPreIssueTaxInvoice(params: Omit<RegistAndPreIssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndPreIssueTaxInvoiceResponse> {
    return this.call<RegistAndPreIssueTaxInvoiceResponse>('RegistAndPreIssueTaxInvoice', params);
  }

  async registAndIssueBrokerTaxInvoice(params: Omit<RegistAndIssueBrokerTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndIssueBrokerTaxInvoiceResponse> {
    return this.call<RegistAndIssueBrokerTaxInvoiceResponse>('RegistAndIssueBrokerTaxInvoice', params);
  }

  async registAndPreIssueBrokerTaxInvoice(params: Omit<RegistAndPreIssueBrokerTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndPreIssueBrokerTaxInvoiceResponse> {
    return this.call<RegistAndPreIssueBrokerTaxInvoiceResponse>('RegistAndPreIssueBrokerTaxInvoice', params);
  }

  async registAndReverseIssueTaxInvoice(params: Omit<RegistAndReverseIssueTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<RegistAndReverseIssueTaxInvoiceResponse> {
    return this.call<RegistAndReverseIssueTaxInvoiceResponse>('RegistAndReverseIssueTaxInvoice', params);
  }

  async registAndIssueTaxInvoiceBulk(params: Omit<RegistAndIssueTaxInvoiceBulk, 'CERTKEY'>): Promise<RegistAndIssueTaxInvoiceBulkResponse> {
    return this.callWithCertKeyOnly<RegistAndIssueTaxInvoiceBulkResponse>('RegistAndIssueTaxInvoiceBulk', params);
  }

  async registAndPreIssueTaxInvoiceBulk(params: Omit<RegistAndPreIssueTaxInvoiceBulk, 'CERTKEY'>): Promise<RegistAndPreIssueTaxInvoiceBulkResponse> {
    return this.callWithCertKeyOnly<RegistAndPreIssueTaxInvoiceBulkResponse>('RegistAndPreIssueTaxInvoiceBulk', params);
  }

  async registAndIssueBrokerTaxInvoiceBulk(params: Omit<RegistAndIssueBrokerTaxInvoiceBulk, 'CERTKEY'>): Promise<RegistAndIssueBrokerTaxInvoiceBulkResponse> {
    return this.callWithCertKeyOnly<RegistAndIssueBrokerTaxInvoiceBulkResponse>('RegistAndIssueBrokerTaxInvoiceBulk', params);
  }

  async registAndPreIssueBrokerTaxInvoiceBulk(params: Omit<RegistAndPreIssueBrokerTaxInvoiceBulk, 'CERTKEY'>): Promise<RegistAndPreIssueBrokerTaxInvoiceBulkResponse> {
    return this.callWithCertKeyOnly<RegistAndPreIssueBrokerTaxInvoiceBulkResponse>('RegistAndPreIssueBrokerTaxInvoiceBulk', params);
  }

  async registAndReverseIssueTaxInvoiceBulk(params: Omit<RegistAndReverseIssueTaxInvoiceBulk, 'CERTKEY'>): Promise<RegistAndReverseIssueTaxInvoiceBulkResponse> {
    return this.callWithCertKeyOnly<RegistAndReverseIssueTaxInvoiceBulkResponse>('RegistAndReverseIssueTaxInvoiceBulk', params);
  }

  async getTaxInvoice(params: Omit<GetTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceResponse> {
    return this.call<GetTaxInvoiceResponse>('GetTaxInvoice', params);
  }

  async getTaxInvoiceIK(params: Omit<GetTaxInvoiceIk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceIkResponse> {
    return this.call<GetTaxInvoiceIkResponse>('GetTaxInvoiceIK', params);
  }

  async getTaxInvoiceNK(params: Omit<GetTaxInvoiceNk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceNkResponse> {
    return this.call<GetTaxInvoiceNkResponse>('GetTaxInvoiceNK', params);
  }

  async getTaxInvoiceState(params: Omit<GetTaxInvoiceState, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceStateResponse> {
    return this.call<GetTaxInvoiceStateResponse>('GetTaxInvoiceState', params);
  }

  async getTaxInvoiceStates(params: Omit<GetTaxInvoiceStates, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceStatesResponse> {
    return this.call<GetTaxInvoiceStatesResponse>('GetTaxInvoiceStates', params);
  }

  async getTaxInvoiceStateEX(params: Omit<GetTaxInvoiceStateEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceStateExResponse> {
    return this.call<GetTaxInvoiceStateExResponse>('GetTaxInvoiceStateEX', params);
  }

  async getTaxInvoiceStatesEX(params: Omit<GetTaxInvoiceStatesEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceStatesExResponse> {
    return this.call<GetTaxInvoiceStatesExResponse>('GetTaxInvoiceStatesEX', params);
  }

  async getTaxInvoiceStatesIK(params: Omit<GetTaxInvoiceStatesIk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceStatesIkResponse> {
    return this.call<GetTaxInvoiceStatesIkResponse>('GetTaxInvoiceStatesIK', params);
  }

  async getTaxInvoiceLog(params: Omit<GetTaxInvoiceLog, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceLogResponse> {
    return this.call<GetTaxInvoiceLogResponse>('GetTaxInvoiceLog', params);
  }

  async getTaxInvoiceLogIK(params: Omit<GetTaxInvoiceLogIk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceLogIkResponse> {
    return this.call<GetTaxInvoiceLogIkResponse>('GetTaxInvoiceLogIK', params);
  }

  async attachFileByFTP(params: Omit<AttachFileByFtp, 'CERTKEY' | 'CorpNum'>): Promise<AttachFileByFtpResponse> {
    return this.call<AttachFileByFtpResponse>('AttachFileByFTP', params);
  }

  async attachFilesByFTP(params: Omit<AttachFilesByFtp, 'CERTKEY' | 'CorpNum'>): Promise<AttachFilesByFtpResponse> {
    return this.call<AttachFilesByFtpResponse>('AttachFilesByFTP', params);
  }

  async deleteAttachFile(params: Omit<DeleteAttachFile, 'CERTKEY' | 'CorpNum'>): Promise<DeleteAttachFileResponse> {
    return this.call<DeleteAttachFileResponse>('DeleteAttachFile', params);
  }

  async deleteAttachFileWithFileIndex(params: Omit<DeleteAttachFileWithFileIndex, 'CERTKEY' | 'CorpNum'>): Promise<DeleteAttachFileWithFileIndexResponse> {
    return this.call<DeleteAttachFileWithFileIndexResponse>('DeleteAttachFileWithFileIndex', params);
  }

  async getAttachedFileList(params: Omit<GetAttachedFileList, 'CERTKEY' | 'CorpNum'>): Promise<GetAttachedFileListResponse> {
    return this.call<GetAttachedFileListResponse>('GetAttachedFileList', params);
  }

  async getAttachedFileListEx(params: Omit<GetAttachedFileListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetAttachedFileListExResponse> {
    return this.call<GetAttachedFileListExResponse>('GetAttachedFileListEx', params);
  }

  async sendEmailEx(params: Omit<SendEmailEx, 'CERTKEY' | 'CorpNum'>): Promise<SendEmailExResponse> {
    return this.call<SendEmailExResponse>('SendEmailEx', params);
  }

  async sendEmailToTruster(params: Omit<SendEmailToTruster, 'CERTKEY' | 'CorpNum'>): Promise<SendEmailToTrusterResponse> {
    return this.call<SendEmailToTrusterResponse>('SendEmailToTruster', params);
  }

  async sendMessageEx(params: Omit<SendMessageEx, 'CERTKEY' | 'CorpNum'>): Promise<SendMessageExResponse> {
    return this.call<SendMessageExResponse>('SendMessageEx', params);
  }

  async sendFaxEx(params: Omit<SendFaxEx, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxExResponse> {
    return this.call<SendFaxExResponse>('SendFaxEx', params);
  }

  async reSendEmail(params: Omit<ReSendEmail, 'CERTKEY' | 'CorpNum'>): Promise<ReSendEmailResponse> {
    return this.call<ReSendEmailResponse>('ReSendEmail', params);
  }

  async reSendSMS(params: Omit<ReSendSms, 'CERTKEY' | 'CorpNum'>): Promise<ReSendSmsResponse> {
    return this.call<ReSendSmsResponse>('ReSendSMS', params);
  }

  async sendInvoiceSMS(params: Omit<SendInvoiceSms, 'CERTKEY' | 'CorpNum'>): Promise<SendInvoiceSmsResponse> {
    return this.call<SendInvoiceSmsResponse>('SendInvoiceSMS', params);
  }

  async sendInvoiceFax(params: Omit<SendInvoiceFax, 'CERTKEY' | 'CorpNum'>): Promise<SendInvoiceFaxResponse> {
    return this.call<SendInvoiceFaxResponse>('SendInvoiceFax', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getTaxInvoicePopUpURL(params: Omit<GetTaxInvoicePopUpUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePopUpUrlResponse> {
    return this.call<GetTaxInvoicePopUpUrlResponse>('GetTaxInvoicePopUpURL', params);
  }

  async getTaxInvoicePopUpURLIK(params: Omit<GetTaxInvoicePopUpUrlik, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePopUpUrlikResponse> {
    return this.call<GetTaxInvoicePopUpUrlikResponse>('GetTaxInvoicePopUpURLIK', params);
  }

  async getTaxInvoicePopUpURLNK(params: Omit<GetTaxInvoicePopUpUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePopUpUrlnkResponse> {
    return this.call<GetTaxInvoicePopUpUrlnkResponse>('GetTaxInvoicePopUpURLNK', params);
  }

  async getTaxInvoicePrintURL(params: Omit<GetTaxInvoicePrintUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePrintUrlResponse> {
    return this.call<GetTaxInvoicePrintUrlResponse>('GetTaxInvoicePrintURL', params);
  }

  async getTaxInvoicePrintURLIK(params: Omit<GetTaxInvoicePrintUrlik, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePrintUrlikResponse> {
    return this.call<GetTaxInvoicePrintUrlikResponse>('GetTaxInvoicePrintURLIK', params);
  }

  async getTaxInvoicePrintURLNK(params: Omit<GetTaxInvoicePrintUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePrintUrlnkResponse> {
    return this.call<GetTaxInvoicePrintUrlnkResponse>('GetTaxInvoicePrintURLNK', params);
  }

  async getTaxInvoicesPrintURL(params: Omit<GetTaxInvoicesPrintUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicesPrintUrlResponse> {
    return this.call<GetTaxInvoicesPrintUrlResponse>('GetTaxInvoicesPrintURL', params);
  }

  async getTaxInvoicesPrintURLNK(params: Omit<GetTaxInvoicesPrintUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicesPrintUrlnkResponse> {
    return this.call<GetTaxInvoicesPrintUrlnkResponse>('GetTaxInvoicesPrintURLNK', params);
  }

  async getTaxinvoiceMailURL(params: Omit<GetTaxinvoiceMailUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxinvoiceMailUrlResponse> {
    return this.call<GetTaxinvoiceMailUrlResponse>('GetTaxinvoiceMailURL', params);
  }

  async getTaxInvoiceMailURLNK(params: Omit<GetTaxInvoiceMailUrlnk, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceMailUrlnkResponse> {
    return this.call<GetTaxInvoiceMailUrlnkResponse>('GetTaxInvoiceMailURLNK', params);
  }

  async getTaxInvoiceSalesList(params: Omit<GetTaxInvoiceSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceSalesListResponse> {
    return this.call<GetTaxInvoiceSalesListResponse>('GetTaxInvoiceSalesList', params);
  }

  async getTaxInvoiceSalesListEx(params: Omit<GetTaxInvoiceSalesListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceSalesListExResponse> {
    return this.call<GetTaxInvoiceSalesListExResponse>('GetTaxInvoiceSalesListEx', params);
  }

  async getTaxInvoicePurchaseList(params: Omit<GetTaxInvoicePurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePurchaseListResponse> {
    return this.call<GetTaxInvoicePurchaseListResponse>('GetTaxInvoicePurchaseList', params);
  }

  async getTaxInvoicePurchaseListEx(params: Omit<GetTaxInvoicePurchaseListEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePurchaseListExResponse> {
    return this.call<GetTaxInvoicePurchaseListExResponse>('GetTaxInvoicePurchaseListEx', params);
  }

  async getDailyTaxInvoiceSalesList(params: Omit<GetDailyTaxInvoiceSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyTaxInvoiceSalesListResponse> {
    return this.call<GetDailyTaxInvoiceSalesListResponse>('GetDailyTaxInvoiceSalesList', params);
  }

  async getDailyTaxInvoicePurchaseList(params: Omit<GetDailyTaxInvoicePurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetDailyTaxInvoicePurchaseListResponse> {
    return this.call<GetDailyTaxInvoicePurchaseListResponse>('GetDailyTaxInvoicePurchaseList', params);
  }

  async getMonthlyTaxInvoiceSalesList(params: Omit<GetMonthlyTaxInvoiceSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyTaxInvoiceSalesListResponse> {
    return this.call<GetMonthlyTaxInvoiceSalesListResponse>('GetMonthlyTaxInvoiceSalesList', params);
  }

  async getMonthlyTaxInvoicePurchaseList(params: Omit<GetMonthlyTaxInvoicePurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyTaxInvoicePurchaseListResponse> {
    return this.call<GetMonthlyTaxInvoicePurchaseListResponse>('GetMonthlyTaxInvoicePurchaseList', params);
  }

  async getPeriodTaxInvoiceSalesList(params: Omit<GetPeriodTaxInvoiceSalesList, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodTaxInvoiceSalesListResponse> {
    return this.call<GetPeriodTaxInvoiceSalesListResponse>('GetPeriodTaxInvoiceSalesList', params);
  }

  async getPeriodTaxInvoicePurchaseList(params: Omit<GetPeriodTaxInvoicePurchaseList, 'CERTKEY' | 'CorpNum'>): Promise<GetPeriodTaxInvoicePurchaseListResponse> {
    return this.call<GetPeriodTaxInvoicePurchaseListResponse>('GetPeriodTaxInvoicePurchaseList', params);
  }

  async getMonthlyCountTaxInvoice(params: Omit<GetMonthlyCountTaxInvoice, 'CERTKEY' | 'CorpNum'>): Promise<GetMonthlyCountTaxInvoiceResponse> {
    return this.call<GetMonthlyCountTaxInvoiceResponse>('GetMonthlyCountTaxInvoice', params);
  }

  async getCanceledTaxInvoiceMgtKey(params: Omit<GetCanceledTaxInvoiceMgtKey, 'CERTKEY' | 'CorpNum'>): Promise<GetCanceledTaxInvoiceMgtKeyResponse> {
    return this.call<GetCanceledTaxInvoiceMgtKeyResponse>('GetCanceledTaxInvoiceMgtKey', params);
  }

  async getTaxInvoiceSalesListByID(params: Omit<GetTaxInvoiceSalesListById, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceSalesListByIdResponse> {
    return this.call<GetTaxInvoiceSalesListByIdResponse>('GetTaxInvoiceSalesListByID', params);
  }

  async getTaxInvoicePurchaseListByID(params: Omit<GetTaxInvoicePurchaseListById, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePurchaseListByIdResponse> {
    return this.call<GetTaxInvoicePurchaseListByIdResponse>('GetTaxInvoicePurchaseListByID', params);
  }

  async getTaxInvoiceSalesListByIDEx(params: Omit<GetTaxInvoiceSalesListByIdEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceSalesListByIdExResponse> {
    return this.call<GetTaxInvoiceSalesListByIdExResponse>('GetTaxInvoiceSalesListByIDEx', params);
  }

  async getTaxInvoicePurchaseListByIDEx(params: Omit<GetTaxInvoicePurchaseListByIdEx, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoicePurchaseListByIdExResponse> {
    return this.call<GetTaxInvoicePurchaseListByIdExResponse>('GetTaxInvoicePurchaseListByIDEx', params);
  }

  async sendToNTS(params: Omit<SendToNts, 'CERTKEY' | 'CorpNum'>): Promise<SendToNtsResponse> {
    return this.call<SendToNtsResponse>('SendToNTS', params);
  }

  async getNTSSendOption(params: Omit<GetNtsSendOption, 'CERTKEY' | 'CorpNum'>): Promise<GetNtsSendOptionResponse> {
    return this.call<GetNtsSendOptionResponse>('GetNTSSendOption', params);
  }

  async changeNTSSendOption(params: Omit<ChangeNtsSendOption, 'CERTKEY' | 'CorpNum'>): Promise<ChangeNtsSendOptionResponse> {
    return this.call<ChangeNtsSendOptionResponse>('ChangeNTSSendOption', params);
  }

  async getEmailPublicKeys(params: Omit<GetEmailPublicKeys, 'CERTKEY'>): Promise<GetEmailPublicKeysResponse> {
    return this.callWithCertKeyOnly<GetEmailPublicKeysResponse>('GetEmailPublicKeys', params);
  }

  async registTaxInvoiceScrap(params: Omit<RegistTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceScrapResponse> {
    return this.call<RegistTaxInvoiceScrapResponse>('RegistTaxInvoiceScrap', params);
  }

  async registTaxInvoiceScrapEx(params: Omit<RegistTaxInvoiceScrapEx, 'CERTKEY' | 'CorpNum'>): Promise<RegistTaxInvoiceScrapExResponse> {
    return this.call<RegistTaxInvoiceScrapExResponse>('RegistTaxInvoiceScrapEx', params);
  }

  async updateTaxInvoiceScrap(params: Omit<UpdateTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<UpdateTaxInvoiceScrapResponse> {
    return this.call<UpdateTaxInvoiceScrapResponse>('UpdateTaxInvoiceScrap', params);
  }

  async updateTaxInvoiceScrapEx(params: Omit<UpdateTaxInvoiceScrapEx, 'CERTKEY' | 'CorpNum'>): Promise<UpdateTaxInvoiceScrapExResponse> {
    return this.call<UpdateTaxInvoiceScrapExResponse>('UpdateTaxInvoiceScrapEx', params);
  }

  async stopTaxInvoiceScrap(params: Omit<StopTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<StopTaxInvoiceScrapResponse> {
    return this.call<StopTaxInvoiceScrapResponse>('StopTaxInvoiceScrap', params);
  }

  async cancelStopTaxInvoiceScrap(params: Omit<CancelStopTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<CancelStopTaxInvoiceScrapResponse> {
    return this.call<CancelStopTaxInvoiceScrapResponse>('CancelStopTaxInvoiceScrap', params);
  }

  async reRegistTaxInvoiceScrap(params: Omit<ReRegistTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<ReRegistTaxInvoiceScrapResponse> {
    return this.call<ReRegistTaxInvoiceScrapResponse>('ReRegistTaxInvoiceScrap', params);
  }

  async getTaxInvoiceScrapRequestURL(params: Omit<GetTaxInvoiceScrapRequestUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetTaxInvoiceScrapRequestUrlResponse> {
    return this.call<GetTaxInvoiceScrapRequestUrlResponse>('GetTaxInvoiceScrapRequestURL', params);
  }

  async refreshTaxInvoiceScrap(params: Omit<RefreshTaxInvoiceScrap, 'CERTKEY' | 'CorpNum'>): Promise<RefreshTaxInvoiceScrapResponse> {
    return this.call<RefreshTaxInvoiceScrapResponse>('RefreshTaxInvoiceScrap', params);
  }

  async makeDocLinkage(params: Omit<MakeDocLinkage, 'CERTKEY' | 'CorpNum'>): Promise<MakeDocLinkageResponse> {
    return this.call<MakeDocLinkageResponse>('MakeDocLinkage', params);
  }

  async removeDocLinkage(params: Omit<RemoveDocLinkage, 'CERTKEY' | 'CorpNum'>): Promise<RemoveDocLinkageResponse> {
    return this.call<RemoveDocLinkageResponse>('RemoveDocLinkage', params);
  }

  async getLinkedDocs(params: Omit<GetLinkedDocs, 'CERTKEY' | 'CorpNum'>): Promise<GetLinkedDocsResponse> {
    return this.call<GetLinkedDocsResponse>('GetLinkedDocs', params);
  }

  async getJicInRegistURL(params: Omit<GetJicInRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetJicInRegistUrlResponse> {
    return this.call<GetJicInRegistUrlResponse>('GetJicInRegistURL', params);
  }

  async getBusinessLicenseRegistURL(params: Omit<GetBusinessLicenseRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBusinessLicenseRegistUrlResponse> {
    return this.call<GetBusinessLicenseRegistUrlResponse>('GetBusinessLicenseRegistURL', params);
  }

  async getBankBookRegistURL(params: Omit<GetBankBookRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBankBookRegistUrlResponse> {
    return this.call<GetBankBookRegistUrlResponse>('GetBankBookRegistURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY' | 'CorpNum'>): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY' | 'CorpNum'>): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY' | 'CorpNum'>): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY' | 'CorpNum'>): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY' | 'CorpNum'>): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY' | 'CorpNum'>): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY' | 'CorpNum'>): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
