// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { SendMessage } from './generated/definitions/SendMessage';
import type { SendMessageResponse } from './generated/definitions/SendMessageResponse';
import type { SendMessages } from './generated/definitions/SendMessages';
import type { SendMessagesResponse } from './generated/definitions/SendMessagesResponse';
import type { SendSmsMessage } from './generated/definitions/SendSmsMessage';
import type { SendSmsMessageResponse } from './generated/definitions/SendSmsMessageResponse';
import type { SendLmsMessage } from './generated/definitions/SendLmsMessage';
import type { SendLmsMessageResponse } from './generated/definitions/SendLmsMessageResponse';
import type { SendMmsMessage } from './generated/definitions/SendMmsMessage';
import type { SendMmsMessageResponse } from './generated/definitions/SendMmsMessageResponse';
import type { SendMmsMessageFromFtp } from './generated/definitions/SendMmsMessageFromFtp';
import type { SendMmsMessageFromFtpResponse } from './generated/definitions/SendMmsMessageFromFtpResponse';
import type { CancelReservedSmsMessage } from './generated/definitions/CancelReservedSmsMessage';
import type { CancelReservedSmsMessageResponse } from './generated/definitions/CancelReservedSmsMessageResponse';
import type { CancelReservedSmsMessageByReceiptNum } from './generated/definitions/CancelReservedSmsMessageByReceiptNum';
import type { CancelReservedSmsMessageByReceiptNumResponse } from './generated/definitions/CancelReservedSmsMessageByReceiptNumResponse';
import type { GetSmsSendState } from './generated/definitions/GetSmsSendState';
import type { GetSmsSendStateResponse } from './generated/definitions/GetSmsSendStateResponse';
import type { GetSmsSendMessage } from './generated/definitions/GetSmsSendMessage';
import type { GetSmsSendMessageResponse } from './generated/definitions/GetSmsSendMessageResponse';
import type { GetSmsSendMessages } from './generated/definitions/GetSmsSendMessages';
import type { GetSmsSendMessagesResponse } from './generated/definitions/GetSmsSendMessagesResponse';
import type { GetMessagesByReceiptNum } from './generated/definitions/GetMessagesByReceiptNum';
import type { GetMessagesByReceiptNumResponse } from './generated/definitions/GetMessagesByReceiptNumResponse';
import type { GetSmsSendMessagesByRefKey } from './generated/definitions/GetSmsSendMessagesByRefKey';
import type { GetSmsSendMessagesByRefKeyResponse } from './generated/definitions/GetSmsSendMessagesByRefKeyResponse';
import type { GetSmsSendMessagesByPaging } from './generated/definitions/GetSmsSendMessagesByPaging';
import type { GetSmsSendMessagesByPagingResponse } from './generated/definitions/GetSmsSendMessagesByPagingResponse';
import type { GetSmsHistoryUrl } from './generated/definitions/GetSmsHistoryUrl';
import type { GetSmsHistoryUrlResponse } from './generated/definitions/GetSmsHistoryUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class SmsClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'SMS';
  }

  static async create(config: BarobillConfig): Promise<SmsClient> {
    const client = new SmsClient(config);
    await client.init();
    return client;
  }

  async sendMessage(params: Omit<SendMessage, 'CERTKEY' | 'CorpNum'>): Promise<SendMessageResponse> {
    return this.call<SendMessageResponse>('SendMessage', params);
  }

  async sendMessages(params: Omit<SendMessages, 'CERTKEY' | 'CorpNum'>): Promise<SendMessagesResponse> {
    return this.call<SendMessagesResponse>('SendMessages', params);
  }

  async sendSMSMessage(params: Omit<SendSmsMessage, 'CERTKEY' | 'CorpNum'>): Promise<SendSmsMessageResponse> {
    return this.call<SendSmsMessageResponse>('SendSMSMessage', params);
  }

  async sendLMSMessage(params: Omit<SendLmsMessage, 'CERTKEY' | 'CorpNum'>): Promise<SendLmsMessageResponse> {
    return this.call<SendLmsMessageResponse>('SendLMSMessage', params);
  }

  async sendMMSMessage(params: Omit<SendMmsMessage, 'CERTKEY' | 'CorpNum'>): Promise<SendMmsMessageResponse> {
    return this.call<SendMmsMessageResponse>('SendMMSMessage', params);
  }

  async sendMMSMessageFromFTP(params: Omit<SendMmsMessageFromFtp, 'CERTKEY' | 'CorpNum'>): Promise<SendMmsMessageFromFtpResponse> {
    return this.call<SendMmsMessageFromFtpResponse>('SendMMSMessageFromFTP', params);
  }

  async cancelReservedSMSMessage(params: Omit<CancelReservedSmsMessage, 'CERTKEY' | 'CorpNum'>): Promise<CancelReservedSmsMessageResponse> {
    return this.call<CancelReservedSmsMessageResponse>('CancelReservedSMSMessage', params);
  }

  async cancelReservedSMSMessageByReceiptNum(params: Omit<CancelReservedSmsMessageByReceiptNum, 'CERTKEY' | 'CorpNum'>): Promise<CancelReservedSmsMessageByReceiptNumResponse> {
    return this.call<CancelReservedSmsMessageByReceiptNumResponse>('CancelReservedSMSMessageByReceiptNum', params);
  }

  async getSMSSendState(params: Omit<GetSmsSendState, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsSendStateResponse> {
    return this.call<GetSmsSendStateResponse>('GetSMSSendState', params);
  }

  async getSMSSendMessage(params: Omit<GetSmsSendMessage, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsSendMessageResponse> {
    return this.call<GetSmsSendMessageResponse>('GetSMSSendMessage', params);
  }

  async getSMSSendMessages(params: Omit<GetSmsSendMessages, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsSendMessagesResponse> {
    return this.call<GetSmsSendMessagesResponse>('GetSMSSendMessages', params);
  }

  async getMessagesByReceiptNum(params: Omit<GetMessagesByReceiptNum, 'CERTKEY' | 'CorpNum'>): Promise<GetMessagesByReceiptNumResponse> {
    return this.call<GetMessagesByReceiptNumResponse>('GetMessagesByReceiptNum', params);
  }

  async getSMSSendMessagesByRefKey(params: Omit<GetSmsSendMessagesByRefKey, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsSendMessagesByRefKeyResponse> {
    return this.call<GetSmsSendMessagesByRefKeyResponse>('GetSMSSendMessagesByRefKey', params);
  }

  async getSMSSendMessagesByPaging(params: Omit<GetSmsSendMessagesByPaging, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsSendMessagesByPagingResponse> {
    return this.call<GetSmsSendMessagesByPagingResponse>('GetSMSSendMessagesByPaging', params);
  }

  async getSMSHistoryURL(params: Omit<GetSmsHistoryUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsHistoryUrlResponse> {
    return this.call<GetSmsHistoryUrlResponse>('GetSMSHistoryURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY' | 'CorpNum'>): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY' | 'CorpNum'>): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY' | 'CorpNum'>): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY' | 'CorpNum'>): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY' | 'CorpNum'>): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY' | 'CorpNum'>): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY' | 'CorpNum'>): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
