// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { GetKakaotalkChannels } from './generated/definitions/GetKakaotalkChannels';
import type { GetKakaotalkChannelsResponse } from './generated/definitions/GetKakaotalkChannelsResponse';
import type { GetKakaotalkChannelManagementUrl } from './generated/definitions/GetKakaotalkChannelManagementUrl';
import type { GetKakaotalkChannelManagementUrlResponse } from './generated/definitions/GetKakaotalkChannelManagementUrlResponse';
import type { GetKakaotalkTemplates } from './generated/definitions/GetKakaotalkTemplates';
import type { GetKakaotalkTemplatesResponse } from './generated/definitions/GetKakaotalkTemplatesResponse';
import type { GetKakaotalkTemplateManagementUrl } from './generated/definitions/GetKakaotalkTemplateManagementUrl';
import type { GetKakaotalkTemplateManagementUrlResponse } from './generated/definitions/GetKakaotalkTemplateManagementUrlResponse';
import type { SendAtKakaotalk } from './generated/definitions/SendAtKakaotalk';
import type { SendAtKakaotalkResponse } from './generated/definitions/SendAtKakaotalkResponse';
import type { SendAtKakaotalkEx } from './generated/definitions/SendAtKakaotalkEx';
import type { SendAtKakaotalkExResponse } from './generated/definitions/SendAtKakaotalkExResponse';
import type { SendAtKakaotalks } from './generated/definitions/SendAtKakaotalks';
import type { SendAtKakaotalksResponse } from './generated/definitions/SendAtKakaotalksResponse';
import type { SendAtKakaotalksEx } from './generated/definitions/SendAtKakaotalksEx';
import type { SendAtKakaotalksExResponse } from './generated/definitions/SendAtKakaotalksExResponse';
import type { SendFtKakaotalk } from './generated/definitions/SendFtKakaotalk';
import type { SendFtKakaotalkResponse } from './generated/definitions/SendFtKakaotalkResponse';
import type { SendFtKakaotalks } from './generated/definitions/SendFtKakaotalks';
import type { SendFtKakaotalksResponse } from './generated/definitions/SendFtKakaotalksResponse';
import type { SendFiKakaotalk } from './generated/definitions/SendFiKakaotalk';
import type { SendFiKakaotalkResponse } from './generated/definitions/SendFiKakaotalkResponse';
import type { SendFiKakaotalks } from './generated/definitions/SendFiKakaotalks';
import type { SendFiKakaotalksResponse } from './generated/definitions/SendFiKakaotalksResponse';
import type { SendFwKakaotalk } from './generated/definitions/SendFwKakaotalk';
import type { SendFwKakaotalkResponse } from './generated/definitions/SendFwKakaotalkResponse';
import type { SendFwKakaotalks } from './generated/definitions/SendFwKakaotalks';
import type { SendFwKakaotalksResponse } from './generated/definitions/SendFwKakaotalksResponse';
import type { CancelReservedKakaotalk } from './generated/definitions/CancelReservedKakaotalk';
import type { CancelReservedKakaotalkResponse } from './generated/definitions/CancelReservedKakaotalkResponse';
import type { GetSendKakaotalk } from './generated/definitions/GetSendKakaotalk';
import type { GetSendKakaotalkResponse } from './generated/definitions/GetSendKakaotalkResponse';
import type { GetSendKakaotalks } from './generated/definitions/GetSendKakaotalks';
import type { GetSendKakaotalksResponse } from './generated/definitions/GetSendKakaotalksResponse';
import type { GetSendKakaotalkEx } from './generated/definitions/GetSendKakaotalkEx';
import type { GetSendKakaotalkExResponse } from './generated/definitions/GetSendKakaotalkExResponse';
import type { GetSendKakaotalksEx } from './generated/definitions/GetSendKakaotalksEx';
import type { GetSendKakaotalksExResponse } from './generated/definitions/GetSendKakaotalksExResponse';
import type { GetKakaotalkHistoryUrl } from './generated/definitions/GetKakaotalkHistoryUrl';
import type { GetKakaotalkHistoryUrlResponse } from './generated/definitions/GetKakaotalkHistoryUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class KakaoTalkClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'KAKAOTALK';
  }

  static async create(config: BarobillConfig): Promise<KakaoTalkClient> {
    const client = new KakaoTalkClient(config);
    await client.init();
    return client;
  }

  async getKakaotalkChannels(params: Omit<GetKakaotalkChannels, 'CERTKEY'> & { CorpNum?: string }): Promise<GetKakaotalkChannelsResponse> {
    return this.call<GetKakaotalkChannelsResponse>('GetKakaotalkChannels', params);
  }

  async getKakaotalkChannelManagementURL(params: Omit<GetKakaotalkChannelManagementUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetKakaotalkChannelManagementUrlResponse> {
    return this.call<GetKakaotalkChannelManagementUrlResponse>('GetKakaotalkChannelManagementURL', params);
  }

  async getKakaotalkTemplates(params: Omit<GetKakaotalkTemplates, 'CERTKEY'> & { CorpNum?: string }): Promise<GetKakaotalkTemplatesResponse> {
    return this.call<GetKakaotalkTemplatesResponse>('GetKakaotalkTemplates', params);
  }

  async getKakaotalkTemplateManagementURL(params: Omit<GetKakaotalkTemplateManagementUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetKakaotalkTemplateManagementUrlResponse> {
    return this.call<GetKakaotalkTemplateManagementUrlResponse>('GetKakaotalkTemplateManagementURL', params);
  }

  async sendATKakaotalk(params: Omit<SendAtKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<SendAtKakaotalkResponse> {
    return this.call<SendAtKakaotalkResponse>('SendATKakaotalk', params);
  }

  async sendATKakaotalkEx(params: Omit<SendAtKakaotalkEx, 'CERTKEY'> & { CorpNum?: string }): Promise<SendAtKakaotalkExResponse> {
    return this.call<SendAtKakaotalkExResponse>('SendATKakaotalkEx', params);
  }

  async sendATKakaotalks(params: Omit<SendAtKakaotalks, 'CERTKEY'> & { CorpNum?: string }): Promise<SendAtKakaotalksResponse> {
    return this.call<SendAtKakaotalksResponse>('SendATKakaotalks', params);
  }

  async sendATKakaotalksEx(params: Omit<SendAtKakaotalksEx, 'CERTKEY'> & { CorpNum?: string }): Promise<SendAtKakaotalksExResponse> {
    return this.call<SendAtKakaotalksExResponse>('SendATKakaotalksEx', params);
  }

  async sendFTKakaotalk(params: Omit<SendFtKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFtKakaotalkResponse> {
    return this.call<SendFtKakaotalkResponse>('SendFTKakaotalk', params);
  }

  async sendFTKakaotalks(params: Omit<SendFtKakaotalks, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFtKakaotalksResponse> {
    return this.call<SendFtKakaotalksResponse>('SendFTKakaotalks', params);
  }

  async sendFIKakaotalk(params: Omit<SendFiKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFiKakaotalkResponse> {
    return this.call<SendFiKakaotalkResponse>('SendFIKakaotalk', params);
  }

  async sendFIKakaotalks(params: Omit<SendFiKakaotalks, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFiKakaotalksResponse> {
    return this.call<SendFiKakaotalksResponse>('SendFIKakaotalks', params);
  }

  async sendFWKakaotalk(params: Omit<SendFwKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFwKakaotalkResponse> {
    return this.call<SendFwKakaotalkResponse>('SendFWKakaotalk', params);
  }

  async sendFWKakaotalks(params: Omit<SendFwKakaotalks, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFwKakaotalksResponse> {
    return this.call<SendFwKakaotalksResponse>('SendFWKakaotalks', params);
  }

  async cancelReservedKakaotalk(params: Omit<CancelReservedKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<CancelReservedKakaotalkResponse> {
    return this.call<CancelReservedKakaotalkResponse>('CancelReservedKakaotalk', params);
  }

  async getSendKakaotalk(params: Omit<GetSendKakaotalk, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSendKakaotalkResponse> {
    return this.call<GetSendKakaotalkResponse>('GetSendKakaotalk', params);
  }

  async getSendKakaotalks(params: Omit<GetSendKakaotalks, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSendKakaotalksResponse> {
    return this.call<GetSendKakaotalksResponse>('GetSendKakaotalks', params);
  }

  async getSendKakaotalkEx(params: Omit<GetSendKakaotalkEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSendKakaotalkExResponse> {
    return this.call<GetSendKakaotalkExResponse>('GetSendKakaotalkEx', params);
  }

  async getSendKakaotalksEx(params: Omit<GetSendKakaotalksEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSendKakaotalksExResponse> {
    return this.call<GetSendKakaotalksExResponse>('GetSendKakaotalksEx', params);
  }

  async getKakaotalkHistoryURL(params: Omit<GetKakaotalkHistoryUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetKakaotalkHistoryUrlResponse> {
    return this.call<GetKakaotalkHistoryUrlResponse>('GetKakaotalkHistoryURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY'> & { CorpNum?: string }): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
