// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { CheckMgtKeyIsExists } from './generated/definitions/CheckMgtKeyIsExists';
import type { CheckMgtKeyIsExistsResponse } from './generated/definitions/CheckMgtKeyIsExistsResponse';
import type { CheckIsValidEDoc } from './generated/definitions/CheckIsValidEDoc';
import type { CheckIsValidEDocResponse } from './generated/definitions/CheckIsValidEDocResponse';
import type { RegistEDoc } from './generated/definitions/RegistEDoc';
import type { RegistEDocResponse } from './generated/definitions/RegistEDocResponse';
import type { RegistEDocWithHtml } from './generated/definitions/RegistEDocWithHtml';
import type { RegistEDocWithHtmlResponse } from './generated/definitions/RegistEDocWithHtmlResponse';
import type { UpdateEDoc } from './generated/definitions/UpdateEDoc';
import type { UpdateEDocResponse } from './generated/definitions/UpdateEDocResponse';
import type { UpdateEDocWithHtml } from './generated/definitions/UpdateEDocWithHtml';
import type { UpdateEDocWithHtmlResponse } from './generated/definitions/UpdateEDocWithHtmlResponse';
import type { DeleteEDoc } from './generated/definitions/DeleteEDoc';
import type { DeleteEDocResponse } from './generated/definitions/DeleteEDocResponse';
import type { IssueEDoc } from './generated/definitions/IssueEDoc';
import type { IssueEDocResponse } from './generated/definitions/IssueEDocResponse';
import type { CancelEDoc } from './generated/definitions/CancelEDoc';
import type { CancelEDocResponse } from './generated/definitions/CancelEDocResponse';
import type { RegistAndIssueEDoc } from './generated/definitions/RegistAndIssueEDoc';
import type { RegistAndIssueEDocResponse } from './generated/definitions/RegistAndIssueEDocResponse';
import type { RegistAndIssueEDocWithHtml } from './generated/definitions/RegistAndIssueEDocWithHtml';
import type { RegistAndIssueEDocWithHtmlResponse } from './generated/definitions/RegistAndIssueEDocWithHtmlResponse';
import type { GetEDoc } from './generated/definitions/GetEDoc';
import type { GetEDocResponse } from './generated/definitions/GetEDocResponse';
import type { GetEDocState } from './generated/definitions/GetEDocState';
import type { GetEDocStateResponse } from './generated/definitions/GetEDocStateResponse';
import type { GetEDocStates } from './generated/definitions/GetEDocStates';
import type { GetEDocStatesResponse } from './generated/definitions/GetEDocStatesResponse';
import type { GetEDocLog } from './generated/definitions/GetEDocLog';
import type { GetEDocLogResponse } from './generated/definitions/GetEDocLogResponse';
import type { AttachFileByFtp } from './generated/definitions/AttachFileByFtp';
import type { AttachFileByFtpResponse } from './generated/definitions/AttachFileByFtpResponse';
import type { AttachFilesByFtp } from './generated/definitions/AttachFilesByFtp';
import type { AttachFilesByFtpResponse } from './generated/definitions/AttachFilesByFtpResponse';
import type { DeleteAttachFile } from './generated/definitions/DeleteAttachFile';
import type { DeleteAttachFileResponse } from './generated/definitions/DeleteAttachFileResponse';
import type { DeleteAttachFileWithFileIndex } from './generated/definitions/DeleteAttachFileWithFileIndex';
import type { DeleteAttachFileWithFileIndexResponse } from './generated/definitions/DeleteAttachFileWithFileIndexResponse';
import type { GetAttachedFileList } from './generated/definitions/GetAttachedFileList';
import type { GetAttachedFileListResponse } from './generated/definitions/GetAttachedFileListResponse';
import type { SendEmailEx } from './generated/definitions/SendEmailEx';
import type { SendEmailExResponse } from './generated/definitions/SendEmailExResponse';
import type { SendMessageEx } from './generated/definitions/SendMessageEx';
import type { SendMessageExResponse } from './generated/definitions/SendMessageExResponse';
import type { SendFaxEx } from './generated/definitions/SendFaxEx';
import type { SendFaxExResponse } from './generated/definitions/SendFaxExResponse';
import type { SendEmail } from './generated/definitions/SendEmail';
import type { SendEmailResponse } from './generated/definitions/SendEmailResponse';
import type { SendEmail2 } from './generated/definitions/SendEmail2';
import type { SendEmail2Response } from './generated/definitions/SendEmail2Response';
import type { SendSms } from './generated/definitions/SendSms';
import type { SendSmsResponse } from './generated/definitions/SendSmsResponse';
import type { SendFax } from './generated/definitions/SendFax';
import type { SendFaxResponse } from './generated/definitions/SendFaxResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetEDocPopUpUrl } from './generated/definitions/GetEDocPopUpUrl';
import type { GetEDocPopUpUrlResponse } from './generated/definitions/GetEDocPopUpUrlResponse';
import type { GetEDocPrintUrl } from './generated/definitions/GetEDocPrintUrl';
import type { GetEDocPrintUrlResponse } from './generated/definitions/GetEDocPrintUrlResponse';
import type { GetEDocsPrintUrl } from './generated/definitions/GetEDocsPrintUrl';
import type { GetEDocsPrintUrlResponse } from './generated/definitions/GetEDocsPrintUrlResponse';
import type { GetEDocMailUrl } from './generated/definitions/GetEDocMailUrl';
import type { GetEDocMailUrlResponse } from './generated/definitions/GetEDocMailUrlResponse';
import type { MakeDocLinkage } from './generated/definitions/MakeDocLinkage';
import type { MakeDocLinkageResponse } from './generated/definitions/MakeDocLinkageResponse';
import type { RemoveDocLinkage } from './generated/definitions/RemoveDocLinkage';
import type { RemoveDocLinkageResponse } from './generated/definitions/RemoveDocLinkageResponse';
import type { GetLinkedDocs } from './generated/definitions/GetLinkedDocs';
import type { GetLinkedDocsResponse } from './generated/definitions/GetLinkedDocsResponse';
import type { GetJicInRegistUrl } from './generated/definitions/GetJicInRegistUrl';
import type { GetJicInRegistUrlResponse } from './generated/definitions/GetJicInRegistUrlResponse';
import type { GetBusinessLicenseRegistUrl } from './generated/definitions/GetBusinessLicenseRegistUrl';
import type { GetBusinessLicenseRegistUrlResponse } from './generated/definitions/GetBusinessLicenseRegistUrlResponse';
import type { GetBankBookRegistUrl } from './generated/definitions/GetBankBookRegistUrl';
import type { GetBankBookRegistUrlResponse } from './generated/definitions/GetBankBookRegistUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class EdocClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'EDOC';
  }

  static async create(config: BarobillConfig): Promise<EdocClient> {
    const client = new EdocClient(config);
    await client.init();
    return client;
  }

  async checkMgtKeyIsExists(params: Omit<CheckMgtKeyIsExists, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckMgtKeyIsExistsResponse> {
    return this.call<CheckMgtKeyIsExistsResponse>('CheckMgtKeyIsExists', params);
  }

  async checkIsValidEDoc(params: Omit<CheckIsValidEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckIsValidEDocResponse> {
    return this.call<CheckIsValidEDocResponse>('CheckIsValidEDoc', params);
  }

  async registEDoc(params: Omit<RegistEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistEDocResponse> {
    return this.call<RegistEDocResponse>('RegistEDoc', params);
  }

  async registEDocWithHtml(params: Omit<RegistEDocWithHtml, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistEDocWithHtmlResponse> {
    return this.call<RegistEDocWithHtmlResponse>('RegistEDocWithHtml', params);
  }

  async updateEDoc(params: Omit<UpdateEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateEDocResponse> {
    return this.call<UpdateEDocResponse>('UpdateEDoc', params);
  }

  async updateEDocWithHtml(params: Omit<UpdateEDocWithHtml, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateEDocWithHtmlResponse> {
    return this.call<UpdateEDocWithHtmlResponse>('UpdateEDocWithHtml', params);
  }

  async deleteEDoc(params: Omit<DeleteEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<DeleteEDocResponse> {
    return this.call<DeleteEDocResponse>('DeleteEDoc', params);
  }

  async issueEDoc(params: Omit<IssueEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<IssueEDocResponse> {
    return this.call<IssueEDocResponse>('IssueEDoc', params);
  }

  async cancelEDoc(params: Omit<CancelEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<CancelEDocResponse> {
    return this.call<CancelEDocResponse>('CancelEDoc', params);
  }

  async registAndIssueEDoc(params: Omit<RegistAndIssueEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistAndIssueEDocResponse> {
    return this.call<RegistAndIssueEDocResponse>('RegistAndIssueEDoc', params);
  }

  async registAndIssueEDocWithHtml(params: Omit<RegistAndIssueEDocWithHtml, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistAndIssueEDocWithHtmlResponse> {
    return this.call<RegistAndIssueEDocWithHtmlResponse>('RegistAndIssueEDocWithHtml', params);
  }

  async getEDoc(params: Omit<GetEDoc, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocResponse> {
    return this.call<GetEDocResponse>('GetEDoc', params);
  }

  async getEDocState(params: Omit<GetEDocState, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocStateResponse> {
    return this.call<GetEDocStateResponse>('GetEDocState', params);
  }

  async getEDocStates(params: Omit<GetEDocStates, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocStatesResponse> {
    return this.call<GetEDocStatesResponse>('GetEDocStates', params);
  }

  async getEDocLog(params: Omit<GetEDocLog, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocLogResponse> {
    return this.call<GetEDocLogResponse>('GetEDocLog', params);
  }

  async attachFileByFTP(params: Omit<AttachFileByFtp, 'CERTKEY'> & { CorpNum?: string }): Promise<AttachFileByFtpResponse> {
    return this.call<AttachFileByFtpResponse>('AttachFileByFTP', params);
  }

  async attachFilesByFTP(params: Omit<AttachFilesByFtp, 'CERTKEY'> & { CorpNum?: string }): Promise<AttachFilesByFtpResponse> {
    return this.call<AttachFilesByFtpResponse>('AttachFilesByFTP', params);
  }

  async deleteAttachFile(params: Omit<DeleteAttachFile, 'CERTKEY'> & { CorpNum?: string }): Promise<DeleteAttachFileResponse> {
    return this.call<DeleteAttachFileResponse>('DeleteAttachFile', params);
  }

  async deleteAttachFileWithFileIndex(params: Omit<DeleteAttachFileWithFileIndex, 'CERTKEY'> & { CorpNum?: string }): Promise<DeleteAttachFileWithFileIndexResponse> {
    return this.call<DeleteAttachFileWithFileIndexResponse>('DeleteAttachFileWithFileIndex', params);
  }

  async getAttachedFileList(params: Omit<GetAttachedFileList, 'CERTKEY'> & { CorpNum?: string }): Promise<GetAttachedFileListResponse> {
    return this.call<GetAttachedFileListResponse>('GetAttachedFileList', params);
  }

  async sendEmailEx(params: Omit<SendEmailEx, 'CERTKEY'> & { CorpNum?: string }): Promise<SendEmailExResponse> {
    return this.call<SendEmailExResponse>('SendEmailEx', params);
  }

  async sendMessageEx(params: Omit<SendMessageEx, 'CERTKEY'> & { CorpNum?: string }): Promise<SendMessageExResponse> {
    return this.call<SendMessageExResponse>('SendMessageEx', params);
  }

  async sendFaxEx(params: Omit<SendFaxEx, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFaxExResponse> {
    return this.call<SendFaxExResponse>('SendFaxEx', params);
  }

  async sendEmail(params: Omit<SendEmail, 'CERTKEY'> & { CorpNum?: string }): Promise<SendEmailResponse> {
    return this.call<SendEmailResponse>('SendEmail', params);
  }

  async sendEmail2(params: Omit<SendEmail2, 'CERTKEY'> & { CorpNum?: string }): Promise<SendEmail2Response> {
    return this.call<SendEmail2Response>('SendEmail2', params);
  }

  async sendSMS(params: Omit<SendSms, 'CERTKEY'> & { CorpNum?: string }): Promise<SendSmsResponse> {
    return this.call<SendSmsResponse>('SendSMS', params);
  }

  async sendFax(params: Omit<SendFax, 'CERTKEY'> & { CorpNum?: string }): Promise<SendFaxResponse> {
    return this.call<SendFaxResponse>('SendFax', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getEDocPopUpURL(params: Omit<GetEDocPopUpUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocPopUpUrlResponse> {
    return this.call<GetEDocPopUpUrlResponse>('GetEDocPopUpURL', params);
  }

  async getEDocPrintURL(params: Omit<GetEDocPrintUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocPrintUrlResponse> {
    return this.call<GetEDocPrintUrlResponse>('GetEDocPrintURL', params);
  }

  async getEDocsPrintURL(params: Omit<GetEDocsPrintUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocsPrintUrlResponse> {
    return this.call<GetEDocsPrintUrlResponse>('GetEDocsPrintURL', params);
  }

  async getEDocMailURL(params: Omit<GetEDocMailUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetEDocMailUrlResponse> {
    return this.call<GetEDocMailUrlResponse>('GetEDocMailURL', params);
  }

  async makeDocLinkage(params: Omit<MakeDocLinkage, 'CERTKEY'> & { CorpNum?: string }): Promise<MakeDocLinkageResponse> {
    return this.call<MakeDocLinkageResponse>('MakeDocLinkage', params);
  }

  async removeDocLinkage(params: Omit<RemoveDocLinkage, 'CERTKEY'> & { CorpNum?: string }): Promise<RemoveDocLinkageResponse> {
    return this.call<RemoveDocLinkageResponse>('RemoveDocLinkage', params);
  }

  async getLinkedDocs(params: Omit<GetLinkedDocs, 'CERTKEY'> & { CorpNum?: string }): Promise<GetLinkedDocsResponse> {
    return this.call<GetLinkedDocsResponse>('GetLinkedDocs', params);
  }

  async getJicInRegistURL(params: Omit<GetJicInRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetJicInRegistUrlResponse> {
    return this.call<GetJicInRegistUrlResponse>('GetJicInRegistURL', params);
  }

  async getBusinessLicenseRegistURL(params: Omit<GetBusinessLicenseRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBusinessLicenseRegistUrlResponse> {
    return this.call<GetBusinessLicenseRegistUrlResponse>('GetBusinessLicenseRegistURL', params);
  }

  async getBankBookRegistURL(params: Omit<GetBankBookRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBankBookRegistUrlResponse> {
    return this.call<GetBankBookRegistUrlResponse>('GetBankBookRegistURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY'> & { CorpNum?: string }): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY'> & { CorpNum?: string }): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY'> & { CorpNum?: string }): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY'> & { CorpNum?: string }): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY'> & { CorpNum?: string }): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY'> & { CorpNum?: string }): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
