// This file is auto-generated by scripts/generate-wrapper.ts
// Do not edit manually.

import { BaseBarobillClient, BarobillConfig, ServiceName } from '@barobill-sdk/core';
import type { SendFaxFromFtp } from './generated/definitions/SendFaxFromFtp';
import type { SendFaxFromFtpResponse } from './generated/definitions/SendFaxFromFtpResponse';
import type { SendFaxesFromFtp } from './generated/definitions/SendFaxesFromFtp';
import type { SendFaxesFromFtpResponse } from './generated/definitions/SendFaxesFromFtpResponse';
import type { SendFaxFromFtpEx } from './generated/definitions/SendFaxFromFtpEx';
import type { SendFaxFromFtpExResponse } from './generated/definitions/SendFaxFromFtpExResponse';
import type { SendFaxesFromFtpEx } from './generated/definitions/SendFaxesFromFtpEx';
import type { SendFaxesFromFtpExResponse } from './generated/definitions/SendFaxesFromFtpExResponse';
import type { ReSendFax } from './generated/definitions/ReSendFax';
import type { ReSendFaxResponse } from './generated/definitions/ReSendFaxResponse';
import type { ReSendFaxEx } from './generated/definitions/ReSendFaxEx';
import type { ReSendFaxExResponse } from './generated/definitions/ReSendFaxExResponse';
import type { CancelReservedFaxMessage } from './generated/definitions/CancelReservedFaxMessage';
import type { CancelReservedFaxMessageResponse } from './generated/definitions/CancelReservedFaxMessageResponse';
import type { GetFaxSendState } from './generated/definitions/GetFaxSendState';
import type { GetFaxSendStateResponse } from './generated/definitions/GetFaxSendStateResponse';
import type { GetFaxMessage } from './generated/definitions/GetFaxMessage';
import type { GetFaxMessageResponse } from './generated/definitions/GetFaxMessageResponse';
import type { GetFaxMessageEx } from './generated/definitions/GetFaxMessageEx';
import type { GetFaxMessageExResponse } from './generated/definitions/GetFaxMessageExResponse';
import type { GetFaxMessageEx2 } from './generated/definitions/GetFaxMessageEx2';
import type { GetFaxMessageEx2Response } from './generated/definitions/GetFaxMessageEx2Response';
import type { GetFaxSendMessages } from './generated/definitions/GetFaxSendMessages';
import type { GetFaxSendMessagesResponse } from './generated/definitions/GetFaxSendMessagesResponse';
import type { GetFaxSendMessagesEx } from './generated/definitions/GetFaxSendMessagesEx';
import type { GetFaxSendMessagesExResponse } from './generated/definitions/GetFaxSendMessagesExResponse';
import type { GetFaxMessagesEx2 } from './generated/definitions/GetFaxMessagesEx2';
import type { GetFaxMessagesEx2Response } from './generated/definitions/GetFaxMessagesEx2Response';
import type { GetFaxSendMessagesByRefKey } from './generated/definitions/GetFaxSendMessagesByRefKey';
import type { GetFaxSendMessagesByRefKeyResponse } from './generated/definitions/GetFaxSendMessagesByRefKeyResponse';
import type { GetFaxSendMessagesByRefKeyEx } from './generated/definitions/GetFaxSendMessagesByRefKeyEx';
import type { GetFaxSendMessagesByRefKeyExResponse } from './generated/definitions/GetFaxSendMessagesByRefKeyExResponse';
import type { GetFaxMessagesByRefKeyEx2 } from './generated/definitions/GetFaxMessagesByRefKeyEx2';
import type { GetFaxMessagesByRefKeyEx2Response } from './generated/definitions/GetFaxMessagesByRefKeyEx2Response';
import type { GetFaxSendMessagesByPaging } from './generated/definitions/GetFaxSendMessagesByPaging';
import type { GetFaxSendMessagesByPagingResponse } from './generated/definitions/GetFaxSendMessagesByPagingResponse';
import type { GetFaxHistoryUrl } from './generated/definitions/GetFaxHistoryUrl';
import type { GetFaxHistoryUrlResponse } from './generated/definitions/GetFaxHistoryUrlResponse';
import type { GetFaxFileUrl } from './generated/definitions/GetFaxFileUrl';
import type { GetFaxFileUrlResponse } from './generated/definitions/GetFaxFileUrlResponse';
import type { CheckCorpIsMember } from './generated/definitions/CheckCorpIsMember';
import type { CheckCorpIsMemberResponse } from './generated/definitions/CheckCorpIsMemberResponse';
import type { RegistCorp } from './generated/definitions/RegistCorp';
import type { RegistCorpResponse } from './generated/definitions/RegistCorpResponse';
import type { AddUserToCorp } from './generated/definitions/AddUserToCorp';
import type { AddUserToCorpResponse } from './generated/definitions/AddUserToCorpResponse';
import type { UpdateCorpInfo } from './generated/definitions/UpdateCorpInfo';
import type { UpdateCorpInfoResponse } from './generated/definitions/UpdateCorpInfoResponse';
import type { UpdateUserInfo } from './generated/definitions/UpdateUserInfo';
import type { UpdateUserInfoResponse } from './generated/definitions/UpdateUserInfoResponse';
import type { UpdateUserPwd } from './generated/definitions/UpdateUserPwd';
import type { UpdateUserPwdResponse } from './generated/definitions/UpdateUserPwdResponse';
import type { ChangeCorpManager } from './generated/definitions/ChangeCorpManager';
import type { ChangeCorpManagerResponse } from './generated/definitions/ChangeCorpManagerResponse';
import type { GetCorpMemberContacts } from './generated/definitions/GetCorpMemberContacts';
import type { GetCorpMemberContactsResponse } from './generated/definitions/GetCorpMemberContactsResponse';
import type { GetBalanceCostAmount } from './generated/definitions/GetBalanceCostAmount';
import type { GetBalanceCostAmountResponse } from './generated/definitions/GetBalanceCostAmountResponse';
import type { GetBalanceCostAmountEx } from './generated/definitions/GetBalanceCostAmountEx';
import type { GetBalanceCostAmountExResponse } from './generated/definitions/GetBalanceCostAmountExResponse';
import type { GetBalanceCostAmountOfInterOp } from './generated/definitions/GetBalanceCostAmountOfInterOp';
import type { GetBalanceCostAmountOfInterOpResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpResponse';
import type { GetBalanceCostAmountOfInterOpEx } from './generated/definitions/GetBalanceCostAmountOfInterOpEx';
import type { GetBalanceCostAmountOfInterOpExResponse } from './generated/definitions/GetBalanceCostAmountOfInterOpExResponse';
import type { CheckChargeable } from './generated/definitions/CheckChargeable';
import type { CheckChargeableResponse } from './generated/definitions/CheckChargeableResponse';
import type { GetChargeUnitCost } from './generated/definitions/GetChargeUnitCost';
import type { GetChargeUnitCostResponse } from './generated/definitions/GetChargeUnitCostResponse';
import type { GetChargeUnitCostEx } from './generated/definitions/GetChargeUnitCostEx';
import type { GetChargeUnitCostExResponse } from './generated/definitions/GetChargeUnitCostExResponse';
import type { GetCashChargeUrl } from './generated/definitions/GetCashChargeUrl';
import type { GetCashChargeUrlResponse } from './generated/definitions/GetCashChargeUrlResponse';
import type { GetCertificateRegistDate } from './generated/definitions/GetCertificateRegistDate';
import type { GetCertificateRegistDateResponse } from './generated/definitions/GetCertificateRegistDateResponse';
import type { GetCertificateExpireDate } from './generated/definitions/GetCertificateExpireDate';
import type { GetCertificateExpireDateResponse } from './generated/definitions/GetCertificateExpireDateResponse';
import type { CheckCertIsValid } from './generated/definitions/CheckCertIsValid';
import type { CheckCertIsValidResponse } from './generated/definitions/CheckCertIsValidResponse';
import type { GetCertificateRegistUrl } from './generated/definitions/GetCertificateRegistUrl';
import type { GetCertificateRegistUrlResponse } from './generated/definitions/GetCertificateRegistUrlResponse';
import type { GetBaroBillUrl } from './generated/definitions/GetBaroBillUrl';
import type { GetBaroBillUrlResponse } from './generated/definitions/GetBaroBillUrlResponse';
import type { GetLoginUrl } from './generated/definitions/GetLoginUrl';
import type { GetLoginUrlResponse } from './generated/definitions/GetLoginUrlResponse';
import type { RegistSmsFromNumber } from './generated/definitions/RegistSmsFromNumber';
import type { RegistSmsFromNumberResponse } from './generated/definitions/RegistSmsFromNumberResponse';
import type { CheckSmsFromNumber } from './generated/definitions/CheckSmsFromNumber';
import type { CheckSmsFromNumberResponse } from './generated/definitions/CheckSmsFromNumberResponse';
import type { GetSmsFromNumbers } from './generated/definitions/GetSmsFromNumbers';
import type { GetSmsFromNumbersResponse } from './generated/definitions/GetSmsFromNumbersResponse';
import type { GetSmsFromNumberUrl } from './generated/definitions/GetSmsFromNumberUrl';
import type { GetSmsFromNumberUrlResponse } from './generated/definitions/GetSmsFromNumberUrlResponse';
import type { CheckFaxFromNumber } from './generated/definitions/CheckFaxFromNumber';
import type { CheckFaxFromNumberResponse } from './generated/definitions/CheckFaxFromNumberResponse';
import type { GetFaxFromNumbers } from './generated/definitions/GetFaxFromNumbers';
import type { GetFaxFromNumbersResponse } from './generated/definitions/GetFaxFromNumbersResponse';
import type { GetFaxFromNumberUrl } from './generated/definitions/GetFaxFromNumberUrl';
import type { GetFaxFromNumberUrlResponse } from './generated/definitions/GetFaxFromNumberUrlResponse';
import type { GetErrString } from './generated/definitions/GetErrString';
import type { GetErrStringResponse } from './generated/definitions/GetErrStringResponse';
import type { Ping } from './generated/definitions/Ping';
import type { PingResponse } from './generated/definitions/PingResponse';

export class FaxClient extends BaseBarobillClient {
  protected get serviceName(): ServiceName {
    return 'FAX';
  }

  static async create(config: BarobillConfig): Promise<FaxClient> {
    const client = new FaxClient(config);
    await client.init();
    return client;
  }

  async sendFaxFromFTP(params: Omit<SendFaxFromFtp, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxFromFtpResponse> {
    return this.call<SendFaxFromFtpResponse>('SendFaxFromFTP', params);
  }

  async sendFaxesFromFTP(params: Omit<SendFaxesFromFtp, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxesFromFtpResponse> {
    return this.call<SendFaxesFromFtpResponse>('SendFaxesFromFTP', params);
  }

  async sendFaxFromFTPEx(params: Omit<SendFaxFromFtpEx, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxFromFtpExResponse> {
    return this.call<SendFaxFromFtpExResponse>('SendFaxFromFTPEx', params);
  }

  async sendFaxesFromFTPEx(params: Omit<SendFaxesFromFtpEx, 'CERTKEY' | 'CorpNum'>): Promise<SendFaxesFromFtpExResponse> {
    return this.call<SendFaxesFromFtpExResponse>('SendFaxesFromFTPEx', params);
  }

  async reSendFax(params: Omit<ReSendFax, 'CERTKEY' | 'CorpNum'>): Promise<ReSendFaxResponse> {
    return this.call<ReSendFaxResponse>('ReSendFax', params);
  }

  async reSendFaxEx(params: Omit<ReSendFaxEx, 'CERTKEY' | 'CorpNum'>): Promise<ReSendFaxExResponse> {
    return this.call<ReSendFaxExResponse>('ReSendFaxEx', params);
  }

  async cancelReservedFaxMessage(params: Omit<CancelReservedFaxMessage, 'CERTKEY' | 'CorpNum'>): Promise<CancelReservedFaxMessageResponse> {
    return this.call<CancelReservedFaxMessageResponse>('CancelReservedFaxMessage', params);
  }

  async getFaxSendState(params: Omit<GetFaxSendState, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendStateResponse> {
    return this.call<GetFaxSendStateResponse>('GetFaxSendState', params);
  }

  async getFaxMessage(params: Omit<GetFaxMessage, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxMessageResponse> {
    return this.call<GetFaxMessageResponse>('GetFaxMessage', params);
  }

  async getFaxMessageEx(params: Omit<GetFaxMessageEx, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxMessageExResponse> {
    return this.call<GetFaxMessageExResponse>('GetFaxMessageEx', params);
  }

  async getFaxMessageEx2(params: Omit<GetFaxMessageEx2, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxMessageEx2Response> {
    return this.call<GetFaxMessageEx2Response>('GetFaxMessageEx2', params);
  }

  async getFaxSendMessages(params: Omit<GetFaxSendMessages, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendMessagesResponse> {
    return this.call<GetFaxSendMessagesResponse>('GetFaxSendMessages', params);
  }

  async getFaxSendMessagesEx(params: Omit<GetFaxSendMessagesEx, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendMessagesExResponse> {
    return this.call<GetFaxSendMessagesExResponse>('GetFaxSendMessagesEx', params);
  }

  async getFaxMessagesEx2(params: Omit<GetFaxMessagesEx2, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxMessagesEx2Response> {
    return this.call<GetFaxMessagesEx2Response>('GetFaxMessagesEx2', params);
  }

  async getFaxSendMessagesByRefKey(params: Omit<GetFaxSendMessagesByRefKey, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendMessagesByRefKeyResponse> {
    return this.call<GetFaxSendMessagesByRefKeyResponse>('GetFaxSendMessagesByRefKey', params);
  }

  async getFaxSendMessagesByRefKeyEx(params: Omit<GetFaxSendMessagesByRefKeyEx, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendMessagesByRefKeyExResponse> {
    return this.call<GetFaxSendMessagesByRefKeyExResponse>('GetFaxSendMessagesByRefKeyEx', params);
  }

  async getFaxMessagesByRefKeyEx2(params: Omit<GetFaxMessagesByRefKeyEx2, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxMessagesByRefKeyEx2Response> {
    return this.call<GetFaxMessagesByRefKeyEx2Response>('GetFaxMessagesByRefKeyEx2', params);
  }

  async getFaxSendMessagesByPaging(params: Omit<GetFaxSendMessagesByPaging, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxSendMessagesByPagingResponse> {
    return this.call<GetFaxSendMessagesByPagingResponse>('GetFaxSendMessagesByPaging', params);
  }

  async getFaxHistoryURL(params: Omit<GetFaxHistoryUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxHistoryUrlResponse> {
    return this.call<GetFaxHistoryUrlResponse>('GetFaxHistoryURL', params);
  }

  async getFaxFileURL(params: Omit<GetFaxFileUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFileUrlResponse> {
    return this.call<GetFaxFileUrlResponse>('GetFaxFileURL', params);
  }

  async checkCorpIsMember(params: Omit<CheckCorpIsMember, 'CERTKEY' | 'CorpNum'>): Promise<CheckCorpIsMemberResponse> {
    return this.call<CheckCorpIsMemberResponse>('CheckCorpIsMember', params);
  }

  async registCorp(params: Omit<RegistCorp, 'CERTKEY' | 'CorpNum'>): Promise<RegistCorpResponse> {
    return this.call<RegistCorpResponse>('RegistCorp', params);
  }

  async addUserToCorp(params: Omit<AddUserToCorp, 'CERTKEY' | 'CorpNum'>): Promise<AddUserToCorpResponse> {
    return this.call<AddUserToCorpResponse>('AddUserToCorp', params);
  }

  async updateCorpInfo(params: Omit<UpdateCorpInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateCorpInfoResponse> {
    return this.call<UpdateCorpInfoResponse>('UpdateCorpInfo', params);
  }

  async updateUserInfo(params: Omit<UpdateUserInfo, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserInfoResponse> {
    return this.call<UpdateUserInfoResponse>('UpdateUserInfo', params);
  }

  async updateUserPWD(params: Omit<UpdateUserPwd, 'CERTKEY' | 'CorpNum'>): Promise<UpdateUserPwdResponse> {
    return this.call<UpdateUserPwdResponse>('UpdateUserPWD', params);
  }

  async changeCorpManager(params: Omit<ChangeCorpManager, 'CERTKEY' | 'CorpNum'>): Promise<ChangeCorpManagerResponse> {
    return this.call<ChangeCorpManagerResponse>('ChangeCorpManager', params);
  }

  async getCorpMemberContacts(params: Omit<GetCorpMemberContacts, 'CERTKEY' | 'CorpNum'>): Promise<GetCorpMemberContactsResponse> {
    return this.call<GetCorpMemberContactsResponse>('GetCorpMemberContacts', params);
  }

  async getBalanceCostAmount(params: Omit<GetBalanceCostAmount, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountResponse> {
    return this.call<GetBalanceCostAmountResponse>('GetBalanceCostAmount', params);
  }

  async getBalanceCostAmountEx(params: Omit<GetBalanceCostAmountEx, 'CERTKEY' | 'CorpNum'>): Promise<GetBalanceCostAmountExResponse> {
    return this.call<GetBalanceCostAmountExResponse>('GetBalanceCostAmountEx', params);
  }

  async getBalanceCostAmountOfInterOP(params: Omit<GetBalanceCostAmountOfInterOp, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpResponse>('GetBalanceCostAmountOfInterOP', params);
  }

  async getBalanceCostAmountOfInterOPEx(params: Omit<GetBalanceCostAmountOfInterOpEx, 'CERTKEY'>): Promise<GetBalanceCostAmountOfInterOpExResponse> {
    return this.callWithCertKeyOnly<GetBalanceCostAmountOfInterOpExResponse>('GetBalanceCostAmountOfInterOPEx', params);
  }

  async checkChargeable(params: Omit<CheckChargeable, 'CERTKEY' | 'CorpNum'>): Promise<CheckChargeableResponse> {
    return this.call<CheckChargeableResponse>('CheckChargeable', params);
  }

  async getChargeUnitCost(params: Omit<GetChargeUnitCost, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostResponse> {
    return this.call<GetChargeUnitCostResponse>('GetChargeUnitCost', params);
  }

  async getChargeUnitCostEx(params: Omit<GetChargeUnitCostEx, 'CERTKEY' | 'CorpNum'>): Promise<GetChargeUnitCostExResponse> {
    return this.call<GetChargeUnitCostExResponse>('GetChargeUnitCostEx', params);
  }

  async getCashChargeURL(params: Omit<GetCashChargeUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCashChargeUrlResponse> {
    return this.call<GetCashChargeUrlResponse>('GetCashChargeURL', params);
  }

  async getCertificateRegistDate(params: Omit<GetCertificateRegistDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistDateResponse> {
    return this.call<GetCertificateRegistDateResponse>('GetCertificateRegistDate', params);
  }

  async getCertificateExpireDate(params: Omit<GetCertificateExpireDate, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateExpireDateResponse> {
    return this.call<GetCertificateExpireDateResponse>('GetCertificateExpireDate', params);
  }

  async checkCERTIsValid(params: Omit<CheckCertIsValid, 'CERTKEY' | 'CorpNum'>): Promise<CheckCertIsValidResponse> {
    return this.call<CheckCertIsValidResponse>('CheckCERTIsValid', params);
  }

  async getCertificateRegistURL(params: Omit<GetCertificateRegistUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetCertificateRegistUrlResponse> {
    return this.call<GetCertificateRegistUrlResponse>('GetCertificateRegistURL', params);
  }

  async getBaroBillURL(params: Omit<GetBaroBillUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetBaroBillUrlResponse> {
    return this.call<GetBaroBillUrlResponse>('GetBaroBillURL', params);
  }

  async getLoginURL(params: Omit<GetLoginUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetLoginUrlResponse> {
    return this.call<GetLoginUrlResponse>('GetLoginURL', params);
  }

  async registSMSFromNumber(params: Omit<RegistSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<RegistSmsFromNumberResponse> {
    return this.call<RegistSmsFromNumberResponse>('RegistSMSFromNumber', params);
  }

  async checkSMSFromNumber(params: Omit<CheckSmsFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckSmsFromNumberResponse> {
    return this.call<CheckSmsFromNumberResponse>('CheckSMSFromNumber', params);
  }

  async getSMSFromNumbers(params: Omit<GetSmsFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumbersResponse> {
    return this.call<GetSmsFromNumbersResponse>('GetSMSFromNumbers', params);
  }

  async getSMSFromNumberURL(params: Omit<GetSmsFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetSmsFromNumberUrlResponse> {
    return this.call<GetSmsFromNumberUrlResponse>('GetSMSFromNumberURL', params);
  }

  async checkFaxFromNumber(params: Omit<CheckFaxFromNumber, 'CERTKEY' | 'CorpNum'>): Promise<CheckFaxFromNumberResponse> {
    return this.call<CheckFaxFromNumberResponse>('CheckFaxFromNumber', params);
  }

  async getFaxFromNumbers(params: Omit<GetFaxFromNumbers, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumbersResponse> {
    return this.call<GetFaxFromNumbersResponse>('GetFaxFromNumbers', params);
  }

  async getFaxFromNumberURL(params: Omit<GetFaxFromNumberUrl, 'CERTKEY' | 'CorpNum'>): Promise<GetFaxFromNumberUrlResponse> {
    return this.call<GetFaxFromNumberUrlResponse>('GetFaxFromNumberURL', params);
  }

  async getErrString(params: Omit<GetErrString, 'CERTKEY'>): Promise<GetErrStringResponse> {
    return this.callWithCertKeyOnly<GetErrStringResponse>('GetErrString', params);
  }

  async ping(): Promise<PingResponse> {
    return this.callRaw<PingResponse>('Ping', {});
  }
}
